### Data Source:

https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

## Importing the libraries

In [1]:
import pandas as pd

## Read csv files

In [2]:
df = pd.read_csv('data/covid19-og.csv')
df

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
0,14/04/2020,14,4,2020,58,3,Afghanistan,AF,AFG,37172386.0
1,13/04/2020,13,4,2020,52,0,Afghanistan,AF,AFG,37172386.0
2,12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0
3,11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0
4,10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0
5,09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0
6,08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0
7,07/04/2020,7,4,2020,38,0,Afghanistan,AF,AFG,37172386.0
8,06/04/2020,6,4,2020,29,2,Afghanistan,AF,AFG,37172386.0
9,05/04/2020,5,4,2020,35,1,Afghanistan,AF,AFG,37172386.0
10,04/04/2020,4,4,2020,0,0,Afghanistan,AF,AFG,37172386.0
11,03/04/2020,3,4,2020,43,0,Afghanistan,AF,AFG,37172386.0
12,02/04/2020,2,4,2020,26,0,Afghanistan,AF,AFG,37172386.0
13,01/04/2020,1,4,2020,25,0,Afghanistan,AF,AFG,37172386.0
14,31/03/2020,31,3,2020,27,0,Afghanistan,AF,AFG,37172386.0
15,30/03/2020,30,3,2020,8,1,Afghanistan,AF,AFG,37172386.0
16,29/03/2020,29,3,2020,15,1,Afghanistan,AF,AFG,37172386.0
17,28/03/2020,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
18,27/03/2020,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
19,26/03/2020,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
20,25/03/2020,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
21,24/03/2020,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
22,23/03/2020,23,3,2020,10,0,Afghanistan,AF,AFG,37172386.0
23,22/03/2020,22,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
24,21/03/2020,21,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
25,20/03/2020,20,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
26,19/03/2020,19,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
27,18/03/2020,18,3,2020,1,0,Afghanistan,AF,AFG,37172386.0
28,17/03/2020,17,3,2020,5,0,Afghanistan,AF,AFG,37172386.0
29,16/03/2020,16,3,2020,6,0,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...,...
10712,23/03/2020,23,3,2020,1,0,Zambia,ZM,ZMB,17351822.0
10713,22/03/2020,22,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10714,21/03/2020,21,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10715,20/03/2020,20,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10716,19/03/2020,19,3,2020,2,0,Zambia,ZM,ZMB,17351822.0
10717,14/04/2020,14,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10718,13/04/2020,13,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10719,12/04/2020,12,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10720,11/04/2020,11,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10721,10/04/2020,10,4,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10722,09/04/2020,9,4,2020,1,1,Zimbabwe,ZW,ZWE,14439018.0
10723,08/04/2020,8,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10724,07/04/2020,7,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10725,06/04/2020,6,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10726,05/04/2020,5,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10727,04/04/2020,4,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10728,03/04/2020,3,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10729,02/04/2020,2,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10730,01/04/2020,1,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10731,31/03/2020,31,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10732,30/03/2020,30,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10733,29/03/2020,29,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10734,28/03/2020,28,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10735,27/03/2020,27,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10736,26/03/2020,26,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10737,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10738,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10739,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10740,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10741,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0

In [5]:
# 1
pd.read_csv('data/covid19-og.csv', header=0)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
0,14/04/2020,14,4,2020,58,3,Afghanistan,AF,AFG,37172386.0
1,13/04/2020,13,4,2020,52,0,Afghanistan,AF,AFG,37172386.0
2,12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0
3,11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0
4,10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0
5,09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0
6,08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0
7,07/04/2020,7,4,2020,38,0,Afghanistan,AF,AFG,37172386.0
8,06/04/2020,6,4,2020,29,2,Afghanistan,AF,AFG,37172386.0
9,05/04/2020,5,4,2020,35,1,Afghanistan,AF,AFG,37172386.0
10,04/04/2020,4,4,2020,0,0,Afghanistan,AF,AFG,37172386.0
11,03/04/2020,3,4,2020,43,0,Afghanistan,AF,AFG,37172386.0
12,02/04/2020,2,4,2020,26,0,Afghanistan,AF,AFG,37172386.0
13,01/04/2020,1,4,2020,25,0,Afghanistan,AF,AFG,37172386.0
14,31/03/2020,31,3,2020,27,0,Afghanistan,AF,AFG,37172386.0
15,30/03/2020,30,3,2020,8,1,Afghanistan,AF,AFG,37172386.0
16,29/03/2020,29,3,2020,15,1,Afghanistan,AF,AFG,37172386.0
17,28/03/2020,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
18,27/03/2020,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
19,26/03/2020,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
20,25/03/2020,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
21,24/03/2020,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
22,23/03/2020,23,3,2020,10,0,Afghanistan,AF,AFG,37172386.0
23,22/03/2020,22,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
24,21/03/2020,21,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
25,20/03/2020,20,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
26,19/03/2020,19,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
27,18/03/2020,18,3,2020,1,0,Afghanistan,AF,AFG,37172386.0
28,17/03/2020,17,3,2020,5,0,Afghanistan,AF,AFG,37172386.0
29,16/03/2020,16,3,2020,6,0,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...,...
10712,23/03/2020,23,3,2020,1,0,Zambia,ZM,ZMB,17351822.0
10713,22/03/2020,22,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10714,21/03/2020,21,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10715,20/03/2020,20,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10716,19/03/2020,19,3,2020,2,0,Zambia,ZM,ZMB,17351822.0
10717,14/04/2020,14,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10718,13/04/2020,13,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10719,12/04/2020,12,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10720,11/04/2020,11,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10721,10/04/2020,10,4,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10722,09/04/2020,9,4,2020,1,1,Zimbabwe,ZW,ZWE,14439018.0
10723,08/04/2020,8,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10724,07/04/2020,7,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10725,06/04/2020,6,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10726,05/04/2020,5,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10727,04/04/2020,4,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10728,03/04/2020,3,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10729,02/04/2020,2,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10730,01/04/2020,1,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10731,31/03/2020,31,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10732,30/03/2020,30,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10733,29/03/2020,29,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10734,28/03/2020,28,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10735,27/03/2020,27,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10736,26/03/2020,26,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10737,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10738,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10739,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10740,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10741,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0

In [8]:
# 2
pd.read_csv('data/covid19-nocols.csv', names=['date', 'day', 'month', 'year', 'cases', 'deaths',
                                             'country', 'code', 'code2', 'population'])

,date,day,month,year,cases,deaths,country,code,code2,population
0,14/04/2020,14,4,2020,58,3,Afghanistan,AF,AFG,37172386.0
1,13/04/2020,13,4,2020,52,0,Afghanistan,AF,AFG,37172386.0
2,12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0
3,11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0
4,10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0
5,09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0
6,08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0
7,07/04/2020,7,4,2020,38,0,Afghanistan,AF,AFG,37172386.0
8,06/04/2020,6,4,2020,29,2,Afghanistan,AF,AFG,37172386.0
9,05/04/2020,5,4,2020,35,1,Afghanistan,AF,AFG,37172386.0
10,04/04/2020,4,4,2020,0,0,Afghanistan,AF,AFG,37172386.0
11,03/04/2020,3,4,2020,43,0,Afghanistan,AF,AFG,37172386.0
12,02/04/2020,2,4,2020,26,0,Afghanistan,AF,AFG,37172386.0
13,01/04/2020,1,4,2020,25,0,Afghanistan,AF,AFG,37172386.0
14,31/03/2020,31,3,2020,27,0,Afghanistan,AF,AFG,37172386.0
15,30/03/2020,30,3,2020,8,1,Afghanistan,AF,AFG,37172386.0
16,29/03/2020,29,3,2020,15,1,Afghanistan,AF,AFG,37172386.0
17,28/03/2020,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
18,27/03/2020,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
19,26/03/2020,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
20,25/03/2020,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
21,24/03/2020,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
22,23/03/2020,23,3,2020,10,0,Afghanistan,AF,AFG,37172386.0
23,22/03/2020,22,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
24,21/03/2020,21,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
25,20/03/2020,20,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
26,19/03/2020,19,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
27,18/03/2020,18,3,2020,1,0,Afghanistan,AF,AFG,37172386.0
28,17/03/2020,17,3,2020,5,0,Afghanistan,AF,AFG,37172386.0
29,16/03/2020,16,3,2020,6,0,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...,...
10712,23/03/2020,23,3,2020,1,0,Zambia,ZM,ZMB,17351822.0
10713,22/03/2020,22,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10714,21/03/2020,21,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10715,20/03/2020,20,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10716,19/03/2020,19,3,2020,2,0,Zambia,ZM,ZMB,17351822.0
10717,14/04/2020,14,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10718,13/04/2020,13,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10719,12/04/2020,12,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10720,11/04/2020,11,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10721,10/04/2020,10,4,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10722,09/04/2020,9,4,2020,1,1,Zimbabwe,ZW,ZWE,14439018.0
10723,08/04/2020,8,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10724,07/04/2020,7,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10725,06/04/2020,6,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10726,05/04/2020,5,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10727,04/04/2020,4,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10728,03/04/2020,3,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10729,02/04/2020,2,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10730,01/04/2020,1,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10731,31/03/2020,31,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10732,30/03/2020,30,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10733,29/03/2020,29,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10734,28/03/2020,28,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10735,27/03/2020,27,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10736,26/03/2020,26,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10737,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10738,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10739,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10740,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10741,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0

In [10]:
# 3

pd.read_csv('data/covid19-og.csv', index_col=0)

,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
dateRep,,,,,,,,,
14/04/2020,14,4,2020,58,3,Afghanistan,AF,AFG,37172386.0
13/04/2020,13,4,2020,52,0,Afghanistan,AF,AFG,37172386.0
12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0
11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0
10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0
09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0
08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0
07/04/2020,7,4,2020,38,0,Afghanistan,AF,AFG,37172386.0
06/04/2020,6,4,2020,29,2,Afghanistan,AF,AFG,37172386.0
05/04/2020,5,4,2020,35,1,Afghanistan,AF,AFG,37172386.0
04/04/2020,4,4,2020,0,0,Afghanistan,AF,AFG,37172386.0
03/04/2020,3,4,2020,43,0,Afghanistan,AF,AFG,37172386.0
02/04/2020,2,4,2020,26,0,Afghanistan,AF,AFG,37172386.0
01/04/2020,1,4,2020,25,0,Afghanistan,AF,AFG,37172386.0
31/03/2020,31,3,2020,27,0,Afghanistan,AF,AFG,37172386.0
30/03/2020,30,3,2020,8,1,Afghanistan,AF,AFG,37172386.0
29/03/2020,29,3,2020,15,1,Afghanistan,AF,AFG,37172386.0
28/03/2020,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
27/03/2020,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
26/03/2020,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
25/03/2020,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
24/03/2020,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
23/03/2020,23,3,2020,10,0,Afghanistan,AF,AFG,37172386.0
22/03/2020,22,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
21/03/2020,21,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
20/03/2020,20,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
19/03/2020,19,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
18/03/2020,18,3,2020,1,0,Afghanistan,AF,AFG,37172386.0
17/03/2020,17,3,2020,5,0,Afghanistan,AF,AFG,37172386.0
16/03/2020,16,3,2020,6,0,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...
23/03/2020,23,3,2020,1,0,Zambia,ZM,ZMB,17351822.0
22/03/2020,22,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
21/03/2020,21,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
20/03/2020,20,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
19/03/2020,19,3,2020,2,0,Zambia,ZM,ZMB,17351822.0
14/04/2020,14,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
13/04/2020,13,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
12/04/2020,12,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
11/04/2020,11,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10/04/2020,10,4,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
09/04/2020,9,4,2020,1,1,Zimbabwe,ZW,ZWE,14439018.0
08/04/2020,8,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
07/04/2020,7,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
06/04/2020,6,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
05/04/2020,5,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
04/04/2020,4,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
03/04/2020,3,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
02/04/2020,2,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
01/04/2020,1,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
31/03/2020,31,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
30/03/2020,30,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
29/03/2020,29,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
28/03/2020,28,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
27/03/2020,27,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
26/03/2020,26,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0

In [12]:
# 4

pd.read_csv('data/covid19-og.csv', usecols=[0, 4, 6])

          dateRep  cases countriesAndTerritories
0      14/04/2020     58             Afghanistan
1      13/04/2020     52             Afghanistan
2      12/04/2020     34             Afghanistan
3      11/04/2020     37             Afghanistan
4      10/04/2020     61             Afghanistan
5      09/04/2020     56             Afghanistan
6      08/04/2020     30             Afghanistan
7      07/04/2020     38             Afghanistan
8      06/04/2020     29             Afghanistan
9      05/04/2020     35             Afghanistan
10     04/04/2020      0             Afghanistan
11     03/04/2020     43             Afghanistan
12     02/04/2020     26             Afghanistan
13     01/04/2020     25             Afghanistan
14     31/03/2020     27             Afghanistan
15     30/03/2020      8             Afghanistan
16     29/03/2020     15             Afghanistan
17     28/03/2020     16             Afghanistan
18     27/03/2020      0             Afghanistan
19     26/03/2020     33             Afghanistan
20     25/03/2020      2             Afghanistan
21     24/03/2020      6             Afghanistan
22     23/03/2020     10             Afghanistan
23     22/03/2020      0             Afghanistan
24     21/03/2020      2             Afghanistan
25     20/03/2020      0             Afghanistan
26     19/03/2020      0             Afghanistan
27     18/03/2020      1             Afghanistan
28     17/03/2020      5             Afghanistan
29     16/03/2020      6             Afghanistan
...           ...    ...                     ...
10712  23/03/2020      1                  Zambia
10713  22/03/2020      0                  Zambia
10714  21/03/2020      0                  Zambia
10715  20/03/2020      0                  Zambia
10716  19/03/2020      2                  Zambia
10717  14/04/2020      3                Zimbabwe
10718  13/04/2020      0                Zimbabwe
10719  12/04/2020      3                Zimbabwe
10720  11/04/2020      0                Zimbabwe
10721  10/04/2020      0                Zimbabwe
10722  09/04/2020      1                Zimbabwe
10723  08/04/2020      1                Zimbabwe
10724  07/04/2020      0                Zimbabwe
10725  06/04/2020      0                Zimbabwe
10726  05/04/2020      0                Zimbabwe
10727  04/04/2020      1                Zimbabwe
10728  03/04/2020      0                Zimbabwe
10729  02/04/2020      0                Zimbabwe
10730  01/04/2020      1                Zimbabwe
10731  31/03/2020      0                Zimbabwe
10732  30/03/2020      0                Zimbabwe
10733  29/03/2020      2                Zimbabwe
10734  28/03/2020      2                Zimbabwe
10735  27/03/2020      0                Zimbabwe
10736  26/03/2020      1                Zimbabwe
10737  25/03/2020      0                Zimbabwe
10738  24/03/2020      0                Zimbabwe
10739  23/03/2020      0                Zimbabwe
10740  22/03/2020      1                Zimbabwe
10741  21/03/2020      1                Zimbabwe

[10742 rows x 3 columns]

In [13]:
# 5

pd.read_csv('data/covid19-og.csv', nrows=15)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
0,14/04/2020,14,4,2020,58,3,Afghanistan,AF,AFG,37172386
1,13/04/2020,13,4,2020,52,0,Afghanistan,AF,AFG,37172386
2,12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386
3,11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386
4,10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386
5,09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386
6,08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386
7,07/04/2020,7,4,2020,38,0,Afghanistan,AF,AFG,37172386
8,06/04/2020,6,4,2020,29,2,Afghanistan,AF,AFG,37172386
9,05/04/2020,5,4,2020,35,1,Afghanistan,AF,AFG,37172386
10,04/04/2020,4,4,2020,0,0,Afghanistan,AF,AFG,37172386
11,03/04/2020,3,4,2020,43,0,Afghanistan,AF,AFG,37172386
12,02/04/2020,2,4,2020,26,0,Afghanistan,AF,AFG,37172386
13,01/04/2020,1,4,2020,25,0,Afghanistan,AF,AFG,37172386
14,31/03/2020,31,3,2020,27,0,Afghanistan,AF,AFG,37172386

In [16]:
# 6

pd.read_csv('data/covid19-skiprows.csv', skiprows=5)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
0,14/04/2020,14,4,2020,58,3,Afghanistan,AF,AFG,37172386.0
1,13/04/2020,13,4,2020,52,0,Afghanistan,AF,AFG,37172386.0
2,12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0
3,11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0
4,10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0
5,09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0
6,08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0
7,07/04/2020,7,4,2020,38,0,Afghanistan,AF,AFG,37172386.0
8,06/04/2020,6,4,2020,29,2,Afghanistan,AF,AFG,37172386.0
9,05/04/2020,5,4,2020,35,1,Afghanistan,AF,AFG,37172386.0
10,04/04/2020,4,4,2020,0,0,Afghanistan,AF,AFG,37172386.0
11,03/04/2020,3,4,2020,43,0,Afghanistan,AF,AFG,37172386.0
12,02/04/2020,2,4,2020,26,0,Afghanistan,AF,AFG,37172386.0
13,01/04/2020,1,4,2020,25,0,Afghanistan,AF,AFG,37172386.0
14,31/03/2020,31,3,2020,27,0,Afghanistan,AF,AFG,37172386.0
15,30/03/2020,30,3,2020,8,1,Afghanistan,AF,AFG,37172386.0
16,29/03/2020,29,3,2020,15,1,Afghanistan,AF,AFG,37172386.0
17,28/03/2020,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
18,27/03/2020,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
19,26/03/2020,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
20,25/03/2020,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
21,24/03/2020,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
22,23/03/2020,23,3,2020,10,0,Afghanistan,AF,AFG,37172386.0
23,22/03/2020,22,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
24,21/03/2020,21,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
25,20/03/2020,20,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
26,19/03/2020,19,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
27,18/03/2020,18,3,2020,1,0,Afghanistan,AF,AFG,37172386.0
28,17/03/2020,17,3,2020,5,0,Afghanistan,AF,AFG,37172386.0
29,16/03/2020,16,3,2020,6,0,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...,...
10712,23/03/2020,23,3,2020,1,0,Zambia,ZM,ZMB,17351822.0
10713,22/03/2020,22,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10714,21/03/2020,21,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10715,20/03/2020,20,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10716,19/03/2020,19,3,2020,2,0,Zambia,ZM,ZMB,17351822.0
10717,14/04/2020,14,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10718,13/04/2020,13,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10719,12/04/2020,12,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10720,11/04/2020,11,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10721,10/04/2020,10,4,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10722,09/04/2020,9,4,2020,1,1,Zimbabwe,ZW,ZWE,14439018.0
10723,08/04/2020,8,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10724,07/04/2020,7,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10725,06/04/2020,6,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10726,05/04/2020,5,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10727,04/04/2020,4,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10728,03/04/2020,3,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10729,02/04/2020,2,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10730,01/04/2020,1,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10731,31/03/2020,31,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10732,30/03/2020,30,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10733,29/03/2020,29,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10734,28/03/2020,28,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10735,27/03/2020,27,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10736,26/03/2020,26,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10737,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10738,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10739,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10740,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10741,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0

In [17]:
# 7

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10742 entries, 0 to 10741
Data columns (total 10 columns):
dateRep                    10742 non-null object
day                        10742 non-null int64
month                      10742 non-null int64
year                       10742 non-null int64
cases                      10742 non-null int64
deaths                     10742 non-null int64
countriesAndTerritories    10742 non-null object
geoId                      10711 non-null object
countryterritoryCode       10635 non-null object
popData2018                10675 non-null float64
dtypes: float64(1), int64(5), object(4)
memory usage: 839.3+ KB

In [22]:
pd.read_csv('data/covid19-og.csv', parse_dates=[0]).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10742 entries, 0 to 10741
Data columns (total 10 columns):
dateRep                    10742 non-null datetime64[ns]
day                        10742 non-null int64
month                      10742 non-null int64
year                       10742 non-null int64
cases                      10742 non-null int64
deaths                     10742 non-null int64
countriesAndTerritories    10742 non-null object
geoId                      10711 non-null object
countryterritoryCode       10635 non-null object
popData2018                10675 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 839.3+ KB

1. header
2. names
3. index_col
4. usecols
5. nrows
6. skiprows
7. parse_dates

## Read Excel files

In [27]:
pd.read_excel('data/covid19.xlsx')

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
0,2020-04-14,14,4,2020,58,3,Afghanistan,AF,AFG,37172386.0
1,2020-04-13,13,4,2020,52,0,Afghanistan,AF,AFG,37172386.0
2,2020-04-12,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0
3,2020-04-11,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0
4,2020-04-10,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0
5,2020-04-09,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0
6,2020-04-08,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0
7,2020-04-07,7,4,2020,38,0,Afghanistan,AF,AFG,37172386.0
8,2020-04-06,6,4,2020,29,2,Afghanistan,AF,AFG,37172386.0
9,2020-04-05,5,4,2020,35,1,Afghanistan,AF,AFG,37172386.0
10,2020-04-04,4,4,2020,0,0,Afghanistan,AF,AFG,37172386.0
11,2020-04-03,3,4,2020,43,0,Afghanistan,AF,AFG,37172386.0
12,2020-04-02,2,4,2020,26,0,Afghanistan,AF,AFG,37172386.0
13,2020-04-01,1,4,2020,25,0,Afghanistan,AF,AFG,37172386.0
14,2020-03-31,31,3,2020,27,0,Afghanistan,AF,AFG,37172386.0
15,2020-03-30,30,3,2020,8,1,Afghanistan,AF,AFG,37172386.0
16,2020-03-29,29,3,2020,15,1,Afghanistan,AF,AFG,37172386.0
17,2020-03-28,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
18,2020-03-27,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
19,2020-03-26,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
20,2020-03-25,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
21,2020-03-24,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
22,2020-03-23,23,3,2020,10,0,Afghanistan,AF,AFG,37172386.0
23,2020-03-22,22,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
24,2020-03-21,21,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
25,2020-03-20,20,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
26,2020-03-19,19,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
27,2020-03-18,18,3,2020,1,0,Afghanistan,AF,AFG,37172386.0
28,2020-03-17,17,3,2020,5,0,Afghanistan,AF,AFG,37172386.0
29,2020-03-16,16,3,2020,6,0,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...,...
10712,2020-03-23,23,3,2020,1,0,Zambia,ZM,ZMB,17351822.0
10713,2020-03-22,22,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10714,2020-03-21,21,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10715,2020-03-20,20,3,2020,0,0,Zambia,ZM,ZMB,17351822.0
10716,2020-03-19,19,3,2020,2,0,Zambia,ZM,ZMB,17351822.0
10717,2020-04-14,14,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10718,2020-04-13,13,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10719,2020-04-12,12,4,2020,3,0,Zimbabwe,ZW,ZWE,14439018.0
10720,2020-04-11,11,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10721,2020-04-10,10,4,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10722,2020-04-09,9,4,2020,1,1,Zimbabwe,ZW,ZWE,14439018.0
10723,2020-04-08,8,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10724,2020-04-07,7,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10725,2020-04-06,6,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10726,2020-04-05,5,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10727,2020-04-04,4,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10728,2020-04-03,3,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10729,2020-04-02,2,4,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10730,2020-04-01,1,4,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10731,2020-03-31,31,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10732,2020-03-30,30,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10733,2020-03-29,29,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10734,2020-03-28,28,3,2020,2,0,Zimbabwe,ZW,ZWE,14439018.0
10735,2020-03-27,27,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10736,2020-03-26,26,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10737,2020-03-25,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10738,2020-03-24,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
10739,2020-03-23,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
10740,2020-03-22,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
10741,2020-03-21,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0

## Read JSON files

In [29]:
pd.read_json('data/admits.json').sort_index()

      gpa    gre toefl workex research  admit
0    6.80  326.0   106      0       3+      0
1    8.24  305.0   114    3.5        0      1
2    6.56  312.0   116      1        2      1
3    7.62  326.0   107      3        3      1
4    6.01  314.0    87      2        2      1
5    6.09  317.0   116      0       3+      0
6   10.90  302.0   118      5        3      1
7    7.01  326.0    89    1.5        2      1
8    6.67  304.0    87    1.5        1      1
9    7.03  301.0    93      0        0      0
10   7.78  329.0    82      4        1      1
11   5.73  327.0   104      4        1      0
12   8.14  328.0    81    0.5        0      1
13   5.52  312.0    93    0.5        2      0
14    NaN  327.0    86      5        0      0
15   6.81  329.0   106    0.5        1      0
16   4.73  319.0    92    1.5        1      1
17   6.62  337.0    84    1.5        2      1
18   5.43  332.0    84    3.5        3      1
19   6.46  331.0    81     5+        1      0
20   6.68  321.0    82    2.5       3+      1
21   6.37  307.0   102     5+        1      1
22   5.94  311.0   118      1        3      0
23   5.59  333.0   116    3.5        2      1
24   7.01  301.0   119    4.5        1      1
25   4.05  331.0   105    0.5        3      1
26   5.86  334.0   101      3        1      0
27   7.06  325.0   106    0.5        0      1
28  10.00  306.0   103      2        0      0
29   6.27  330.0   106      2        0      1
..    ...    ...   ...    ...      ...    ...
70   9.05  330.0   119      2       3+      1
71   6.41  302.0    98   None        0      1
72    NaN  317.0   102      3        1      0
73   7.24  312.0   107      1        0      0
74   6.56  332.0   112    1.5        1      0
75   8.86  321.0   104     5+       3+      0
76   6.54  302.0    83      1       3+      0
77   8.32  310.0   119    4.5        3      0
78   8.86  325.0   103      0       3+      1
79   7.63  326.0    88      1        1      0
80   6.69  319.0    88    0.5        0      0
81   6.62  339.0    80    4.5        3      1
82   4.11  318.0   115      1       3+      1
83   6.81  307.0   116     5+        2      1
84   7.05  321.0   117     5+        0      0
85   5.29  307.0    88   None       3+      1
86   7.60  304.0    97      5        1      0
87   7.89  315.0    98    0.5        3      1
88   6.75  318.0    95    3.5        1      0
89   8.28  332.0   103    4.5        1      1
90   8.08  324.0   109    3.5        2      0
91   6.48  320.0    98      2       3+      0
92   5.27  301.0   118    3.5        2      0
93   6.11  315.0    95     5+        3      0
94   7.00  300.0    94    4.5       3+      1
95   4.96  303.0    92    0.5        2      0
96   6.13  323.0   119     5+        1      1
97   8.65  333.0   119    2.5        2      1
98   5.79  303.0    91      5     none      1
99   6.05  332.0    99    4.5        0      1

[100 rows x 6 columns]

In [30]:
admits = pd.read_csv('data/admits.csv')
admits

      gpa    gre toefl workex research  admit
0    6.80  326.0   106      0       3+      0
1    8.24  305.0   114    3.5        0      1
2    6.56  312.0   116      1        2      1
3    7.62  326.0   107      3        3      1
4    6.01  314.0    87      2        2      1
5    6.09  317.0   116      0       3+      0
6   10.90  302.0   118      5        3      1
7    7.01  326.0    89    1.5        2      1
8    6.67  304.0    87    1.5        1      1
9    7.03  301.0    93      0        0      0
10   7.78  329.0    82      4        1      1
11   5.73  327.0   104      4        1      0
12   8.14  328.0    81    0.5        0      1
13   5.52  312.0    93    0.5        2      0
14    NaN  327.0    86      5        0      0
15   6.81  329.0   106    0.5        1      0
16   4.73  319.0    92    1.5        1      1
17   6.62  337.0    84    1.5        2      1
18   5.43  332.0    84    3.5        3      1
19   6.46  331.0    81     5+        1      0
20   6.68  321.0    82    2.5       3+      1
21   6.37  307.0   102     5+        1      1
22   5.94  311.0   118      1        3      0
23   5.59  333.0   116    3.5        2      1
24   7.01  301.0   119    4.5        1      1
25   4.05  331.0   105    0.5        3      1
26   5.86  334.0   101      3        1      0
27   7.06  325.0   106    0.5        0      1
28  10.00  306.0   103      2        0      0
29   6.27  330.0   106      2        0      1
..    ...    ...   ...    ...      ...    ...
70   9.05  330.0   119      2       3+      1
71   6.41  302.0    98    NaN        0      1
72    NaN  317.0   102      3        1      0
73   7.24  312.0   107      1        0      0
74   6.56  332.0   112    1.5        1      0
75   8.86  321.0   104     5+       3+      0
76   6.54  302.0    83      1       3+      0
77   8.32  310.0   119    4.5        3      0
78   8.86  325.0   103      0       3+      1
79   7.63  326.0    88      1        1      0
80   6.69  319.0    88    0.5        0      0
81   6.62  339.0    80    4.5        3      1
82   4.11  318.0   115      1       3+      1
83   6.81  307.0   116     5+        2      1
84   7.05  321.0   117     5+        0      0
85   5.29  307.0    88    NaN       3+      1
86   7.60  304.0    97      5        1      0
87   7.89  315.0    98    0.5        3      1
88   6.75  318.0    95    3.5        1      0
89   8.28  332.0   103    4.5        1      1
90   8.08  324.0   109    3.5        2      0
91   6.48  320.0    98      2       3+      0
92   5.27  301.0   118    3.5        2      0
93   6.11  315.0    95     5+        3      0
94   7.00  300.0    94    4.5       3+      1
95   4.96  303.0    92    0.5        2      0
96   6.13  323.0   119     5+        1      1
97   8.65  333.0   119    2.5        2      1
98   5.79  303.0    91      5     none      1
99   6.05  332.0    99    4.5        0      1

[100 rows x 6 columns]

In [31]:
admits.to_json(orient='columns')

'{"gpa":{"0":6.8,"1":8.24,"2":6.56,"3":7.62,"4":6.01,"5":6.09,"6":10.9,"7":7.01,"8":6.67,"9":7.03,"10":7.78,"11":5.73,"12":8.14,"13":5.52,"14":null,"15":6.81,"16":4.73,"17":6.62,"18":5.43,"19":6.46,"20":6.68,"21":6.37,"22":5.94,"23":5.59,"24":7.01,"25":4.05,"26":5.86,"27":7.06,"28":10.0,"29":6.27,"30":8.92,"31":6.75,"32":4.84,"33":7.78,"34":6.18,"35":7.68,"36":6.74,"37":8.79,"38":9.16,"39":5.67,"40":8.62,"41":6.41,"42":7.34,"43":7.53,"44":6.92,"45":8.51,"46":7.98,"47":5.1,"48":8.88,"49":5.85,"50":8.94,"51":5.48,"52":8.03,"53":7.08,"54":5.19,"55":null,"56":6.38,"57":7.68,"58":6.53,"59":6.17,"60":7.18,"61":6.86,"62":5.94,"63":6.89,"64":5.41,"65":7.69,"66":7.07,"67":6.77,"68":5.5,"69":8.31,"70":9.05,"71":6.41,"72":null,"73":7.24,"74":6.56,"75":8.86,"76":6.54,"77":8.32,"78":8.86,"79":7.63,"80":6.69,"81":6.62,"82":4.11,"83":6.81,"84":7.05,"85":5.29,"86":7.6,"87":7.89,"88":6.75,"89":8.28,"90":8.08,"91":6.48,"92":5.27,"93":6.11,"94":7.0,"95":4.96,"96":6.13,"97":8.65,"98":5.79,"99":6.05},"gre":{"0":326.0,"1":305.0,"2":312.0,"3":326.0,"4":314.0,"5":317.0,"6":302.0,"7":326.0,"8":304.0,"9":301.0,"10":329.0,"11":327.0,"12":328.0,"13":312.0,"14":327.0,"15":329.0,"16":319.0,"17":337.0,"18":332.0,"19":331.0,"20":321.0,"21":307.0,"22":311.0,"23":333.0,"24":301.0,"25":331.0,"26":334.0,"27":325.0,"28":306.0,"29":330.0,"30":311.0,"31":309.0,"32":338.0,"33":305.0,"34":306.0,"35":317.0,"36":329.0,"37":328.0,"38":324.0,"39":326.0,"40":329.0,"41":321.0,"42":338.0,"43":301.0,"44":312.0,"45":null,"46":301.0,"47":339.0,"48":326.0,"49":306.0,"50":307.0,"51":306.0,"52":307.0,"53":301.0,"54":322.0,"55":324.0,"56":332.0,"57":326.0,"58":308.0,"59":307.0,"60":326.0,"61":305.0,"62":327.0,"63":319.0,"64":334.0,"65":305.0,"66":331.0,"67":315.0,"68":318.0,"69":323.0,"70":330.0,"71":302.0,"72":317.0,"73":312.0,"74":332.0,"75":321.0,"76":302.0,"77":310.0,"78":325.0,"79":326.0,"80":319.0,"81":339.0,"82":318.0,"83":307.0,"84":321.0,"85":307.0,"86":304.0,"87":315.0,"88":318.0,"89":332.0,"90":324.0,"91":320.0,"92":301.0,"93":315.0,"94":300.0,"95":303.0,"96":323.0,"97":333.0,"98":303.0,"99":332.0},"toefl":{"0":"106","1":"114","2":"116","3":"107","4":"87","5":"116","6":"118","7":"89","8":"87","9":"93","10":"82","11":"104","12":"81","13":"93","14":"86","15":"106","16":"92","17":"84","18":"84","19":"81","20":"82","21":"102","22":"118","23":"116","24":"119","25":"105","26":"101","27":"106","28":"103","29":"106","30":"91","31":"92","32":"90","33":"116","34":"105","35":"86","36":"89","37":"119","38":"96","39":"101","40":"108","41":"94","42":"108","43":"109","44":"100","45":"99","46":"111","47":"111","48":"87","49":"111","50":"115","51":"90","52":"82","53":"86","54":"93","55":"117","56":"84","57":"101","58":"88","59":"106","60":"110","61":"89","62":"82","63":"94","64":"110","65":"119","66":"92","67":"101","68":"na","69":"97","70":"119","71":"98","72":"102","73":"107","74":"112","75":"104","76":"83","77":"119","78":"103","79":"88","80":"88","81":"80","82":"115","83":"116","84":"117","85":"88","86":"97","87":"98","88":"95","89":"103","90":"109","91":"98","92":"118","93":"95","94":"94","95":"92","96":"119","97":"119","98":"91","99":"99"},"workex":{"0":"0","1":"3.5","2":"1","3":"3","4":"2","5":"0","6":"5","7":"1.5","8":"1.5","9":"0","10":"4","11":"4","12":"0.5","13":"0.5","14":"5","15":"0.5","16":"1.5","17":"1.5","18":"3.5","19":"5+","20":"2.5","21":"5+","22":"1","23":"3.5","24":"4.5","25":"0.5","26":"3","27":"0.5","28":"2","29":"2","30":"0","31":"3.5","32":"3.5","33":"5","34":"4","35":"2","36":"5","37":"1","38":"3","39":"5+","40":"4","41":"2.5","42":"0","43":"4","44":"4.5","45":"4","46":"5","47":"3","48":"2.5","49":"1.5","50":"3","51":"3.5","52":"0.5","53":"2.5","54":"4.5","55":"4.5","56":"2","57":"1.5","58":"3.5","59":"4","60":"5","61":"0","62":"3","63":"3","64":"4","65":"1.5","66":"2","67":"0.5","68":"5+","69":"3","70":"2","71":null,"72":"3","73":"1","74":"1.5","75":"5+","76":"1","77":"4.5","78":"0","79":"1","80":"0.5","81":"4.5","82":"1","83":"5+","84":"5+","85":null,"86":"5","87":"0.5","88":"3.5","89":"4.5","90":"3.5","91":"2","92":"3.5","93":"5+","94":"4.5","95":"0.5","96":"5+","97":"2.5","98":"5","99":"4.5"},"research":{"0":"3+","1":"0","2":"2","3":"3","4":"2","5":"3+","6":"3","7":"2","8":"1","9":"0","10":"1","11":"1","12":"0","13":"2","14":"0","15":"1","16":"1","17":"2","18":"3","19":"1","20":"3+","21":"1","22":"3","23":"2","24":"1","25":"3","26":"1","27":"0","28":"0","29":"0","30":"3+","31":"3+","32":"1","33":"0","34":"2","35":"3+","36":"none","37":"3","38":"3+","39":"3+","40":"3+","41":"1","42":"3","43":"0","44":"0","45":"none","46":"0","47":"2","48":"2","49":"3","50":"0","51":"2","52":"2","53":"2","54":"3+","55":"0","56":"2","57":"1","58":"2","59":"3","60":"2","61":"3","62":"1","63":"3","64":"1","65":"0","66":"3+","67":"0","68":"1","69":"0","70":"3+","71":"0","72":"1","73":"0","74":"1","75":"3+","76":"3+","77":"3","78":"3+","79":"1","80":"0","81":"3","82":"3+","83":"2","84":"0","85":"3+","86":"1","87":"3","88":"1","89":"1","90":"2","91":"3+","92":"2","93":"3","94":"3+","95":"2","96":"1","97":"2","98":"none","99":"0"},"admit":{"0":0,"1":1,"2":1,"3":1,"4":1,"5":0,"6":1,"7":1,"8":1,"9":0,"10":1,"11":0,"12":1,"13":0,"14":0,"15":0,"16":1,"17":1,"18":1,"19":0,"20":1,"21":1,"22":0,"23":1,"24":1,"25":1,"26":0,"27":1,"28":0,"29":1,"30":1,"31":1,"32":0,"33":0,"34":0,"35":1,"36":0,"37":1,"38":1,"39":0,"40":1,"41":0,"42":0,"43":1,"44":0,"45":0,"46":1,"47":1,"48":1,"49":1,"50":1,"51":1,"52":1,"53":0,"54":1,"55":1,"56":1,"57":0,"58":0,"59":0,"60":0,"61":0,"62":1,"63":1,"64":1,"65":1,"66":0,"67":1,"68":1,"69":1,"70":1,"71":1,"72":0,"73":0,"74":0,"75":0,"76":0,"77":0,"78":1,"79":0,"80":0,"81":1,"82":1,"83":1,"84":0,"85":1,"86":0,"87":1,"88":0,"89":1,"90":0,"91":0,"92":0,"93":0,"94":1,"95":0,"96":1,"97":1,"98":1,"99":1}}'

In [32]:
admits.to_json(orient='values')

'[[6.8,326.0,"106","0","3+",0],[8.24,305.0,"114","3.5","0",1],[6.56,312.0,"116","1","2",1],[7.62,326.0,"107","3","3",1],[6.01,314.0,"87","2","2",1],[6.09,317.0,"116","0","3+",0],[10.9,302.0,"118","5","3",1],[7.01,326.0,"89","1.5","2",1],[6.67,304.0,"87","1.5","1",1],[7.03,301.0,"93","0","0",0],[7.78,329.0,"82","4","1",1],[5.73,327.0,"104","4","1",0],[8.14,328.0,"81","0.5","0",1],[5.52,312.0,"93","0.5","2",0],[null,327.0,"86","5","0",0],[6.81,329.0,"106","0.5","1",0],[4.73,319.0,"92","1.5","1",1],[6.62,337.0,"84","1.5","2",1],[5.43,332.0,"84","3.5","3",1],[6.46,331.0,"81","5+","1",0],[6.68,321.0,"82","2.5","3+",1],[6.37,307.0,"102","5+","1",1],[5.94,311.0,"118","1","3",0],[5.59,333.0,"116","3.5","2",1],[7.01,301.0,"119","4.5","1",1],[4.05,331.0,"105","0.5","3",1],[5.86,334.0,"101","3","1",0],[7.06,325.0,"106","0.5","0",1],[10.0,306.0,"103","2","0",0],[6.27,330.0,"106","2","0",1],[8.92,311.0,"91","0","3+",1],[6.75,309.0,"92","3.5","3+",1],[4.84,338.0,"90","3.5","1",0],[7.78,305.0,"116","5","0",0],[6.18,306.0,"105","4","2",0],[7.68,317.0,"86","2","3+",1],[6.74,329.0,"89","5","none",0],[8.79,328.0,"119","1","3",1],[9.16,324.0,"96","3","3+",1],[5.67,326.0,"101","5+","3+",0],[8.62,329.0,"108","4","3+",1],[6.41,321.0,"94","2.5","1",0],[7.34,338.0,"108","0","3",0],[7.53,301.0,"109","4","0",1],[6.92,312.0,"100","4.5","0",0],[8.51,null,"99","4","none",0],[7.98,301.0,"111","5","0",1],[5.1,339.0,"111","3","2",1],[8.88,326.0,"87","2.5","2",1],[5.85,306.0,"111","1.5","3",1],[8.94,307.0,"115","3","0",1],[5.48,306.0,"90","3.5","2",1],[8.03,307.0,"82","0.5","2",1],[7.08,301.0,"86","2.5","2",0],[5.19,322.0,"93","4.5","3+",1],[null,324.0,"117","4.5","0",1],[6.38,332.0,"84","2","2",1],[7.68,326.0,"101","1.5","1",0],[6.53,308.0,"88","3.5","2",0],[6.17,307.0,"106","4","3",0],[7.18,326.0,"110","5","2",0],[6.86,305.0,"89","0","3",0],[5.94,327.0,"82","3","1",1],[6.89,319.0,"94","3","3",1],[5.41,334.0,"110","4","1",1],[7.69,305.0,"119","1.5","0",1],[7.07,331.0,"92","2","3+",0],[6.77,315.0,"101","0.5","0",1],[5.5,318.0,"na","5+","1",1],[8.31,323.0,"97","3","0",1],[9.05,330.0,"119","2","3+",1],[6.41,302.0,"98",null,"0",1],[null,317.0,"102","3","1",0],[7.24,312.0,"107","1","0",0],[6.56,332.0,"112","1.5","1",0],[8.86,321.0,"104","5+","3+",0],[6.54,302.0,"83","1","3+",0],[8.32,310.0,"119","4.5","3",0],[8.86,325.0,"103","0","3+",1],[7.63,326.0,"88","1","1",0],[6.69,319.0,"88","0.5","0",0],[6.62,339.0,"80","4.5","3",1],[4.11,318.0,"115","1","3+",1],[6.81,307.0,"116","5+","2",1],[7.05,321.0,"117","5+","0",0],[5.29,307.0,"88",null,"3+",1],[7.6,304.0,"97","5","1",0],[7.89,315.0,"98","0.5","3",1],[6.75,318.0,"95","3.5","1",0],[8.28,332.0,"103","4.5","1",1],[8.08,324.0,"109","3.5","2",0],[6.48,320.0,"98","2","3+",0],[5.27,301.0,"118","3.5","2",0],[6.11,315.0,"95","5+","3",0],[7.0,300.0,"94","4.5","3+",1],[4.96,303.0,"92","0.5","2",0],[6.13,323.0,"119","5+","1",1],[8.65,333.0,"119","2.5","2",1],[5.79,303.0,"91","5","none",1],[6.05,332.0,"99","4.5","0",1]]'

In [33]:
admits.to_json(orient='index')

'{"0":{"gpa":6.8,"gre":326.0,"toefl":"106","workex":"0","research":"3+","admit":0},"1":{"gpa":8.24,"gre":305.0,"toefl":"114","workex":"3.5","research":"0","admit":1},"2":{"gpa":6.56,"gre":312.0,"toefl":"116","workex":"1","research":"2","admit":1},"3":{"gpa":7.62,"gre":326.0,"toefl":"107","workex":"3","research":"3","admit":1},"4":{"gpa":6.01,"gre":314.0,"toefl":"87","workex":"2","research":"2","admit":1},"5":{"gpa":6.09,"gre":317.0,"toefl":"116","workex":"0","research":"3+","admit":0},"6":{"gpa":10.9,"gre":302.0,"toefl":"118","workex":"5","research":"3","admit":1},"7":{"gpa":7.01,"gre":326.0,"toefl":"89","workex":"1.5","research":"2","admit":1},"8":{"gpa":6.67,"gre":304.0,"toefl":"87","workex":"1.5","research":"1","admit":1},"9":{"gpa":7.03,"gre":301.0,"toefl":"93","workex":"0","research":"0","admit":0},"10":{"gpa":7.78,"gre":329.0,"toefl":"82","workex":"4","research":"1","admit":1},"11":{"gpa":5.73,"gre":327.0,"toefl":"104","workex":"4","research":"1","admit":0},"12":{"gpa":8.14,"gre":328.0,"toefl":"81","workex":"0.5","research":"0","admit":1},"13":{"gpa":5.52,"gre":312.0,"toefl":"93","workex":"0.5","research":"2","admit":0},"14":{"gpa":null,"gre":327.0,"toefl":"86","workex":"5","research":"0","admit":0},"15":{"gpa":6.81,"gre":329.0,"toefl":"106","workex":"0.5","research":"1","admit":0},"16":{"gpa":4.73,"gre":319.0,"toefl":"92","workex":"1.5","research":"1","admit":1},"17":{"gpa":6.62,"gre":337.0,"toefl":"84","workex":"1.5","research":"2","admit":1},"18":{"gpa":5.43,"gre":332.0,"toefl":"84","workex":"3.5","research":"3","admit":1},"19":{"gpa":6.46,"gre":331.0,"toefl":"81","workex":"5+","research":"1","admit":0},"20":{"gpa":6.68,"gre":321.0,"toefl":"82","workex":"2.5","research":"3+","admit":1},"21":{"gpa":6.37,"gre":307.0,"toefl":"102","workex":"5+","research":"1","admit":1},"22":{"gpa":5.94,"gre":311.0,"toefl":"118","workex":"1","research":"3","admit":0},"23":{"gpa":5.59,"gre":333.0,"toefl":"116","workex":"3.5","research":"2","admit":1},"24":{"gpa":7.01,"gre":301.0,"toefl":"119","workex":"4.5","research":"1","admit":1},"25":{"gpa":4.05,"gre":331.0,"toefl":"105","workex":"0.5","research":"3","admit":1},"26":{"gpa":5.86,"gre":334.0,"toefl":"101","workex":"3","research":"1","admit":0},"27":{"gpa":7.06,"gre":325.0,"toefl":"106","workex":"0.5","research":"0","admit":1},"28":{"gpa":10.0,"gre":306.0,"toefl":"103","workex":"2","research":"0","admit":0},"29":{"gpa":6.27,"gre":330.0,"toefl":"106","workex":"2","research":"0","admit":1},"30":{"gpa":8.92,"gre":311.0,"toefl":"91","workex":"0","research":"3+","admit":1},"31":{"gpa":6.75,"gre":309.0,"toefl":"92","workex":"3.5","research":"3+","admit":1},"32":{"gpa":4.84,"gre":338.0,"toefl":"90","workex":"3.5","research":"1","admit":0},"33":{"gpa":7.78,"gre":305.0,"toefl":"116","workex":"5","research":"0","admit":0},"34":{"gpa":6.18,"gre":306.0,"toefl":"105","workex":"4","research":"2","admit":0},"35":{"gpa":7.68,"gre":317.0,"toefl":"86","workex":"2","research":"3+","admit":1},"36":{"gpa":6.74,"gre":329.0,"toefl":"89","workex":"5","research":"none","admit":0},"37":{"gpa":8.79,"gre":328.0,"toefl":"119","workex":"1","research":"3","admit":1},"38":{"gpa":9.16,"gre":324.0,"toefl":"96","workex":"3","research":"3+","admit":1},"39":{"gpa":5.67,"gre":326.0,"toefl":"101","workex":"5+","research":"3+","admit":0},"40":{"gpa":8.62,"gre":329.0,"toefl":"108","workex":"4","research":"3+","admit":1},"41":{"gpa":6.41,"gre":321.0,"toefl":"94","workex":"2.5","research":"1","admit":0},"42":{"gpa":7.34,"gre":338.0,"toefl":"108","workex":"0","research":"3","admit":0},"43":{"gpa":7.53,"gre":301.0,"toefl":"109","workex":"4","research":"0","admit":1},"44":{"gpa":6.92,"gre":312.0,"toefl":"100","workex":"4.5","research":"0","admit":0},"45":{"gpa":8.51,"gre":null,"toefl":"99","workex":"4","research":"none","admit":0},"46":{"gpa":7.98,"gre":301.0,"toefl":"111","workex":"5","research":"0","admit":1},"47":{"gpa":5.1,"gre":339.0,"toefl":"111","workex":"3","research":"2","admit":1},"48":{"gpa":8.88,"gre":326.0,"toefl":"87","workex":"2.5","research":"2","admit":1},"49":{"gpa":5.85,"gre":306.0,"toefl":"111","workex":"1.5","research":"3","admit":1},"50":{"gpa":8.94,"gre":307.0,"toefl":"115","workex":"3","research":"0","admit":1},"51":{"gpa":5.48,"gre":306.0,"toefl":"90","workex":"3.5","research":"2","admit":1},"52":{"gpa":8.03,"gre":307.0,"toefl":"82","workex":"0.5","research":"2","admit":1},"53":{"gpa":7.08,"gre":301.0,"toefl":"86","workex":"2.5","research":"2","admit":0},"54":{"gpa":5.19,"gre":322.0,"toefl":"93","workex":"4.5","research":"3+","admit":1},"55":{"gpa":null,"gre":324.0,"toefl":"117","workex":"4.5","research":"0","admit":1},"56":{"gpa":6.38,"gre":332.0,"toefl":"84","workex":"2","research":"2","admit":1},"57":{"gpa":7.68,"gre":326.0,"toefl":"101","workex":"1.5","research":"1","admit":0},"58":{"gpa":6.53,"gre":308.0,"toefl":"88","workex":"3.5","research":"2","admit":0},"59":{"gpa":6.17,"gre":307.0,"toefl":"106","workex":"4","research":"3","admit":0},"60":{"gpa":7.18,"gre":326.0,"toefl":"110","workex":"5","research":"2","admit":0},"61":{"gpa":6.86,"gre":305.0,"toefl":"89","workex":"0","research":"3","admit":0},"62":{"gpa":5.94,"gre":327.0,"toefl":"82","workex":"3","research":"1","admit":1},"63":{"gpa":6.89,"gre":319.0,"toefl":"94","workex":"3","research":"3","admit":1},"64":{"gpa":5.41,"gre":334.0,"toefl":"110","workex":"4","research":"1","admit":1},"65":{"gpa":7.69,"gre":305.0,"toefl":"119","workex":"1.5","research":"0","admit":1},"66":{"gpa":7.07,"gre":331.0,"toefl":"92","workex":"2","research":"3+","admit":0},"67":{"gpa":6.77,"gre":315.0,"toefl":"101","workex":"0.5","research":"0","admit":1},"68":{"gpa":5.5,"gre":318.0,"toefl":"na","workex":"5+","research":"1","admit":1},"69":{"gpa":8.31,"gre":323.0,"toefl":"97","workex":"3","research":"0","admit":1},"70":{"gpa":9.05,"gre":330.0,"toefl":"119","workex":"2","research":"3+","admit":1},"71":{"gpa":6.41,"gre":302.0,"toefl":"98","workex":null,"research":"0","admit":1},"72":{"gpa":null,"gre":317.0,"toefl":"102","workex":"3","research":"1","admit":0},"73":{"gpa":7.24,"gre":312.0,"toefl":"107","workex":"1","research":"0","admit":0},"74":{"gpa":6.56,"gre":332.0,"toefl":"112","workex":"1.5","research":"1","admit":0},"75":{"gpa":8.86,"gre":321.0,"toefl":"104","workex":"5+","research":"3+","admit":0},"76":{"gpa":6.54,"gre":302.0,"toefl":"83","workex":"1","research":"3+","admit":0},"77":{"gpa":8.32,"gre":310.0,"toefl":"119","workex":"4.5","research":"3","admit":0},"78":{"gpa":8.86,"gre":325.0,"toefl":"103","workex":"0","research":"3+","admit":1},"79":{"gpa":7.63,"gre":326.0,"toefl":"88","workex":"1","research":"1","admit":0},"80":{"gpa":6.69,"gre":319.0,"toefl":"88","workex":"0.5","research":"0","admit":0},"81":{"gpa":6.62,"gre":339.0,"toefl":"80","workex":"4.5","research":"3","admit":1},"82":{"gpa":4.11,"gre":318.0,"toefl":"115","workex":"1","research":"3+","admit":1},"83":{"gpa":6.81,"gre":307.0,"toefl":"116","workex":"5+","research":"2","admit":1},"84":{"gpa":7.05,"gre":321.0,"toefl":"117","workex":"5+","research":"0","admit":0},"85":{"gpa":5.29,"gre":307.0,"toefl":"88","workex":null,"research":"3+","admit":1},"86":{"gpa":7.6,"gre":304.0,"toefl":"97","workex":"5","research":"1","admit":0},"87":{"gpa":7.89,"gre":315.0,"toefl":"98","workex":"0.5","research":"3","admit":1},"88":{"gpa":6.75,"gre":318.0,"toefl":"95","workex":"3.5","research":"1","admit":0},"89":{"gpa":8.28,"gre":332.0,"toefl":"103","workex":"4.5","research":"1","admit":1},"90":{"gpa":8.08,"gre":324.0,"toefl":"109","workex":"3.5","research":"2","admit":0},"91":{"gpa":6.48,"gre":320.0,"toefl":"98","workex":"2","research":"3+","admit":0},"92":{"gpa":5.27,"gre":301.0,"toefl":"118","workex":"3.5","research":"2","admit":0},"93":{"gpa":6.11,"gre":315.0,"toefl":"95","workex":"5+","research":"3","admit":0},"94":{"gpa":7.0,"gre":300.0,"toefl":"94","workex":"4.5","research":"3+","admit":1},"95":{"gpa":4.96,"gre":303.0,"toefl":"92","workex":"0.5","research":"2","admit":0},"96":{"gpa":6.13,"gre":323.0,"toefl":"119","workex":"5+","research":"1","admit":1},"97":{"gpa":8.65,"gre":333.0,"toefl":"119","workex":"2.5","research":"2","admit":1},"98":{"gpa":5.79,"gre":303.0,"toefl":"91","workex":"5","research":"none","admit":1},"99":{"gpa":6.05,"gre":332.0,"toefl":"99","workex":"4.5","research":"0","admit":1}}'

In [37]:
admits.to_json('data/split_json.json', orient='split')

In [39]:
pd.read_json('data/split_json.json', orient='split')

      gpa    gre toefl workex research  admit
0    6.80  326.0   106      0       3+      0
1    8.24  305.0   114    3.5        0      1
2    6.56  312.0   116      1        2      1
3    7.62  326.0   107      3        3      1
4    6.01  314.0    87      2        2      1
5    6.09  317.0   116      0       3+      0
6   10.90  302.0   118      5        3      1
7    7.01  326.0    89    1.5        2      1
8    6.67  304.0    87    1.5        1      1
9    7.03  301.0    93      0        0      0
10   7.78  329.0    82      4        1      1
11   5.73  327.0   104      4        1      0
12   8.14  328.0    81    0.5        0      1
13   5.52  312.0    93    0.5        2      0
14    NaN  327.0    86      5        0      0
15   6.81  329.0   106    0.5        1      0
16   4.73  319.0    92    1.5        1      1
17   6.62  337.0    84    1.5        2      1
18   5.43  332.0    84    3.5        3      1
19   6.46  331.0    81     5+        1      0
20   6.68  321.0    82    2.5       3+      1
21   6.37  307.0   102     5+        1      1
22   5.94  311.0   118      1        3      0
23   5.59  333.0   116    3.5        2      1
24   7.01  301.0   119    4.5        1      1
25   4.05  331.0   105    0.5        3      1
26   5.86  334.0   101      3        1      0
27   7.06  325.0   106    0.5        0      1
28  10.00  306.0   103      2        0      0
29   6.27  330.0   106      2        0      1
..    ...    ...   ...    ...      ...    ...
70   9.05  330.0   119      2       3+      1
71   6.41  302.0    98   None        0      1
72    NaN  317.0   102      3        1      0
73   7.24  312.0   107      1        0      0
74   6.56  332.0   112    1.5        1      0
75   8.86  321.0   104     5+       3+      0
76   6.54  302.0    83      1       3+      0
77   8.32  310.0   119    4.5        3      0
78   8.86  325.0   103      0       3+      1
79   7.63  326.0    88      1        1      0
80   6.69  319.0    88    0.5        0      0
81   6.62  339.0    80    4.5        3      1
82   4.11  318.0   115      1       3+      1
83   6.81  307.0   116     5+        2      1
84   7.05  321.0   117     5+        0      0
85   5.29  307.0    88   None       3+      1
86   7.60  304.0    97      5        1      0
87   7.89  315.0    98    0.5        3      1
88   6.75  318.0    95    3.5        1      0
89   8.28  332.0   103    4.5        1      1
90   8.08  324.0   109    3.5        2      0
91   6.48  320.0    98      2       3+      0
92   5.27  301.0   118    3.5        2      0
93   6.11  315.0    95     5+        3      0
94   7.00  300.0    94    4.5       3+      1
95   4.96  303.0    92    0.5        2      0
96   6.13  323.0   119     5+        1      1
97   8.65  333.0   119    2.5        2      1
98   5.79  303.0    91      5     none      1
99   6.05  332.0    99    4.5        0      1

[100 rows x 6 columns]

In [35]:
admits.to_json(orient='records')

'[{"gpa":6.8,"gre":326.0,"toefl":"106","workex":"0","research":"3+","admit":0},{"gpa":8.24,"gre":305.0,"toefl":"114","workex":"3.5","research":"0","admit":1},{"gpa":6.56,"gre":312.0,"toefl":"116","workex":"1","research":"2","admit":1},{"gpa":7.62,"gre":326.0,"toefl":"107","workex":"3","research":"3","admit":1},{"gpa":6.01,"gre":314.0,"toefl":"87","workex":"2","research":"2","admit":1},{"gpa":6.09,"gre":317.0,"toefl":"116","workex":"0","research":"3+","admit":0},{"gpa":10.9,"gre":302.0,"toefl":"118","workex":"5","research":"3","admit":1},{"gpa":7.01,"gre":326.0,"toefl":"89","workex":"1.5","research":"2","admit":1},{"gpa":6.67,"gre":304.0,"toefl":"87","workex":"1.5","research":"1","admit":1},{"gpa":7.03,"gre":301.0,"toefl":"93","workex":"0","research":"0","admit":0},{"gpa":7.78,"gre":329.0,"toefl":"82","workex":"4","research":"1","admit":1},{"gpa":5.73,"gre":327.0,"toefl":"104","workex":"4","research":"1","admit":0},{"gpa":8.14,"gre":328.0,"toefl":"81","workex":"0.5","research":"0","admit":1},{"gpa":5.52,"gre":312.0,"toefl":"93","workex":"0.5","research":"2","admit":0},{"gpa":null,"gre":327.0,"toefl":"86","workex":"5","research":"0","admit":0},{"gpa":6.81,"gre":329.0,"toefl":"106","workex":"0.5","research":"1","admit":0},{"gpa":4.73,"gre":319.0,"toefl":"92","workex":"1.5","research":"1","admit":1},{"gpa":6.62,"gre":337.0,"toefl":"84","workex":"1.5","research":"2","admit":1},{"gpa":5.43,"gre":332.0,"toefl":"84","workex":"3.5","research":"3","admit":1},{"gpa":6.46,"gre":331.0,"toefl":"81","workex":"5+","research":"1","admit":0},{"gpa":6.68,"gre":321.0,"toefl":"82","workex":"2.5","research":"3+","admit":1},{"gpa":6.37,"gre":307.0,"toefl":"102","workex":"5+","research":"1","admit":1},{"gpa":5.94,"gre":311.0,"toefl":"118","workex":"1","research":"3","admit":0},{"gpa":5.59,"gre":333.0,"toefl":"116","workex":"3.5","research":"2","admit":1},{"gpa":7.01,"gre":301.0,"toefl":"119","workex":"4.5","research":"1","admit":1},{"gpa":4.05,"gre":331.0,"toefl":"105","workex":"0.5","research":"3","admit":1},{"gpa":5.86,"gre":334.0,"toefl":"101","workex":"3","research":"1","admit":0},{"gpa":7.06,"gre":325.0,"toefl":"106","workex":"0.5","research":"0","admit":1},{"gpa":10.0,"gre":306.0,"toefl":"103","workex":"2","research":"0","admit":0},{"gpa":6.27,"gre":330.0,"toefl":"106","workex":"2","research":"0","admit":1},{"gpa":8.92,"gre":311.0,"toefl":"91","workex":"0","research":"3+","admit":1},{"gpa":6.75,"gre":309.0,"toefl":"92","workex":"3.5","research":"3+","admit":1},{"gpa":4.84,"gre":338.0,"toefl":"90","workex":"3.5","research":"1","admit":0},{"gpa":7.78,"gre":305.0,"toefl":"116","workex":"5","research":"0","admit":0},{"gpa":6.18,"gre":306.0,"toefl":"105","workex":"4","research":"2","admit":0},{"gpa":7.68,"gre":317.0,"toefl":"86","workex":"2","research":"3+","admit":1},{"gpa":6.74,"gre":329.0,"toefl":"89","workex":"5","research":"none","admit":0},{"gpa":8.79,"gre":328.0,"toefl":"119","workex":"1","research":"3","admit":1},{"gpa":9.16,"gre":324.0,"toefl":"96","workex":"3","research":"3+","admit":1},{"gpa":5.67,"gre":326.0,"toefl":"101","workex":"5+","research":"3+","admit":0},{"gpa":8.62,"gre":329.0,"toefl":"108","workex":"4","research":"3+","admit":1},{"gpa":6.41,"gre":321.0,"toefl":"94","workex":"2.5","research":"1","admit":0},{"gpa":7.34,"gre":338.0,"toefl":"108","workex":"0","research":"3","admit":0},{"gpa":7.53,"gre":301.0,"toefl":"109","workex":"4","research":"0","admit":1},{"gpa":6.92,"gre":312.0,"toefl":"100","workex":"4.5","research":"0","admit":0},{"gpa":8.51,"gre":null,"toefl":"99","workex":"4","research":"none","admit":0},{"gpa":7.98,"gre":301.0,"toefl":"111","workex":"5","research":"0","admit":1},{"gpa":5.1,"gre":339.0,"toefl":"111","workex":"3","research":"2","admit":1},{"gpa":8.88,"gre":326.0,"toefl":"87","workex":"2.5","research":"2","admit":1},{"gpa":5.85,"gre":306.0,"toefl":"111","workex":"1.5","research":"3","admit":1},{"gpa":8.94,"gre":307.0,"toefl":"115","workex":"3","research":"0","admit":1},{"gpa":5.48,"gre":306.0,"toefl":"90","workex":"3.5","research":"2","admit":1},{"gpa":8.03,"gre":307.0,"toefl":"82","workex":"0.5","research":"2","admit":1},{"gpa":7.08,"gre":301.0,"toefl":"86","workex":"2.5","research":"2","admit":0},{"gpa":5.19,"gre":322.0,"toefl":"93","workex":"4.5","research":"3+","admit":1},{"gpa":null,"gre":324.0,"toefl":"117","workex":"4.5","research":"0","admit":1},{"gpa":6.38,"gre":332.0,"toefl":"84","workex":"2","research":"2","admit":1},{"gpa":7.68,"gre":326.0,"toefl":"101","workex":"1.5","research":"1","admit":0},{"gpa":6.53,"gre":308.0,"toefl":"88","workex":"3.5","research":"2","admit":0},{"gpa":6.17,"gre":307.0,"toefl":"106","workex":"4","research":"3","admit":0},{"gpa":7.18,"gre":326.0,"toefl":"110","workex":"5","research":"2","admit":0},{"gpa":6.86,"gre":305.0,"toefl":"89","workex":"0","research":"3","admit":0},{"gpa":5.94,"gre":327.0,"toefl":"82","workex":"3","research":"1","admit":1},{"gpa":6.89,"gre":319.0,"toefl":"94","workex":"3","research":"3","admit":1},{"gpa":5.41,"gre":334.0,"toefl":"110","workex":"4","research":"1","admit":1},{"gpa":7.69,"gre":305.0,"toefl":"119","workex":"1.5","research":"0","admit":1},{"gpa":7.07,"gre":331.0,"toefl":"92","workex":"2","research":"3+","admit":0},{"gpa":6.77,"gre":315.0,"toefl":"101","workex":"0.5","research":"0","admit":1},{"gpa":5.5,"gre":318.0,"toefl":"na","workex":"5+","research":"1","admit":1},{"gpa":8.31,"gre":323.0,"toefl":"97","workex":"3","research":"0","admit":1},{"gpa":9.05,"gre":330.0,"toefl":"119","workex":"2","research":"3+","admit":1},{"gpa":6.41,"gre":302.0,"toefl":"98","workex":null,"research":"0","admit":1},{"gpa":null,"gre":317.0,"toefl":"102","workex":"3","research":"1","admit":0},{"gpa":7.24,"gre":312.0,"toefl":"107","workex":"1","research":"0","admit":0},{"gpa":6.56,"gre":332.0,"toefl":"112","workex":"1.5","research":"1","admit":0},{"gpa":8.86,"gre":321.0,"toefl":"104","workex":"5+","research":"3+","admit":0},{"gpa":6.54,"gre":302.0,"toefl":"83","workex":"1","research":"3+","admit":0},{"gpa":8.32,"gre":310.0,"toefl":"119","workex":"4.5","research":"3","admit":0},{"gpa":8.86,"gre":325.0,"toefl":"103","workex":"0","research":"3+","admit":1},{"gpa":7.63,"gre":326.0,"toefl":"88","workex":"1","research":"1","admit":0},{"gpa":6.69,"gre":319.0,"toefl":"88","workex":"0.5","research":"0","admit":0},{"gpa":6.62,"gre":339.0,"toefl":"80","workex":"4.5","research":"3","admit":1},{"gpa":4.11,"gre":318.0,"toefl":"115","workex":"1","research":"3+","admit":1},{"gpa":6.81,"gre":307.0,"toefl":"116","workex":"5+","research":"2","admit":1},{"gpa":7.05,"gre":321.0,"toefl":"117","workex":"5+","research":"0","admit":0},{"gpa":5.29,"gre":307.0,"toefl":"88","workex":null,"research":"3+","admit":1},{"gpa":7.6,"gre":304.0,"toefl":"97","workex":"5","research":"1","admit":0},{"gpa":7.89,"gre":315.0,"toefl":"98","workex":"0.5","research":"3","admit":1},{"gpa":6.75,"gre":318.0,"toefl":"95","workex":"3.5","research":"1","admit":0},{"gpa":8.28,"gre":332.0,"toefl":"103","workex":"4.5","research":"1","admit":1},{"gpa":8.08,"gre":324.0,"toefl":"109","workex":"3.5","research":"2","admit":0},{"gpa":6.48,"gre":320.0,"toefl":"98","workex":"2","research":"3+","admit":0},{"gpa":5.27,"gre":301.0,"toefl":"118","workex":"3.5","research":"2","admit":0},{"gpa":6.11,"gre":315.0,"toefl":"95","workex":"5+","research":"3","admit":0},{"gpa":7.0,"gre":300.0,"toefl":"94","workex":"4.5","research":"3+","admit":1},{"gpa":4.96,"gre":303.0,"toefl":"92","workex":"0.5","research":"2","admit":0},{"gpa":6.13,"gre":323.0,"toefl":"119","workex":"5+","research":"1","admit":1},{"gpa":8.65,"gre":333.0,"toefl":"119","workex":"2.5","research":"2","admit":1},{"gpa":5.79,"gre":303.0,"toefl":"91","workex":"5","research":"none","admit":1},{"gpa":6.05,"gre":332.0,"toefl":"99","workex":"4.5","research":"0","admit":1}]'

In [36]:
admits.to_json(orient='table')

'{"schema": {"fields":[{"name":"index","type":"integer"},{"name":"gpa","type":"number"},{"name":"gre","type":"number"},{"name":"toefl","type":"string"},{"name":"workex","type":"string"},{"name":"research","type":"string"},{"name":"admit","type":"integer"}],"primaryKey":["index"],"pandas_version":"0.20.0"}, "data": [{"index":0,"gpa":6.8,"gre":326.0,"toefl":"106","workex":"0","research":"3+","admit":0},{"index":1,"gpa":8.24,"gre":305.0,"toefl":"114","workex":"3.5","research":"0","admit":1},{"index":2,"gpa":6.56,"gre":312.0,"toefl":"116","workex":"1","research":"2","admit":1},{"index":3,"gpa":7.62,"gre":326.0,"toefl":"107","workex":"3","research":"3","admit":1},{"index":4,"gpa":6.01,"gre":314.0,"toefl":"87","workex":"2","research":"2","admit":1},{"index":5,"gpa":6.09,"gre":317.0,"toefl":"116","workex":"0","research":"3+","admit":0},{"index":6,"gpa":10.9,"gre":302.0,"toefl":"118","workex":"5","research":"3","admit":1},{"index":7,"gpa":7.01,"gre":326.0,"toefl":"89","workex":"1.5","research":"2","admit":1},{"index":8,"gpa":6.67,"gre":304.0,"toefl":"87","workex":"1.5","research":"1","admit":1},{"index":9,"gpa":7.03,"gre":301.0,"toefl":"93","workex":"0","research":"0","admit":0},{"index":10,"gpa":7.78,"gre":329.0,"toefl":"82","workex":"4","research":"1","admit":1},{"index":11,"gpa":5.73,"gre":327.0,"toefl":"104","workex":"4","research":"1","admit":0},{"index":12,"gpa":8.14,"gre":328.0,"toefl":"81","workex":"0.5","research":"0","admit":1},{"index":13,"gpa":5.52,"gre":312.0,"toefl":"93","workex":"0.5","research":"2","admit":0},{"index":14,"gpa":null,"gre":327.0,"toefl":"86","workex":"5","research":"0","admit":0},{"index":15,"gpa":6.81,"gre":329.0,"toefl":"106","workex":"0.5","research":"1","admit":0},{"index":16,"gpa":4.73,"gre":319.0,"toefl":"92","workex":"1.5","research":"1","admit":1},{"index":17,"gpa":6.62,"gre":337.0,"toefl":"84","workex":"1.5","research":"2","admit":1},{"index":18,"gpa":5.43,"gre":332.0,"toefl":"84","workex":"3.5","research":"3","admit":1},{"index":19,"gpa":6.46,"gre":331.0,"toefl":"81","workex":"5+","research":"1","admit":0},{"index":20,"gpa":6.68,"gre":321.0,"toefl":"82","workex":"2.5","research":"3+","admit":1},{"index":21,"gpa":6.37,"gre":307.0,"toefl":"102","workex":"5+","research":"1","admit":1},{"index":22,"gpa":5.94,"gre":311.0,"toefl":"118","workex":"1","research":"3","admit":0},{"index":23,"gpa":5.59,"gre":333.0,"toefl":"116","workex":"3.5","research":"2","admit":1},{"index":24,"gpa":7.01,"gre":301.0,"toefl":"119","workex":"4.5","research":"1","admit":1},{"index":25,"gpa":4.05,"gre":331.0,"toefl":"105","workex":"0.5","research":"3","admit":1},{"index":26,"gpa":5.86,"gre":334.0,"toefl":"101","workex":"3","research":"1","admit":0},{"index":27,"gpa":7.06,"gre":325.0,"toefl":"106","workex":"0.5","research":"0","admit":1},{"index":28,"gpa":10.0,"gre":306.0,"toefl":"103","workex":"2","research":"0","admit":0},{"index":29,"gpa":6.27,"gre":330.0,"toefl":"106","workex":"2","research":"0","admit":1},{"index":30,"gpa":8.92,"gre":311.0,"toefl":"91","workex":"0","research":"3+","admit":1},{"index":31,"gpa":6.75,"gre":309.0,"toefl":"92","workex":"3.5","research":"3+","admit":1},{"index":32,"gpa":4.84,"gre":338.0,"toefl":"90","workex":"3.5","research":"1","admit":0},{"index":33,"gpa":7.78,"gre":305.0,"toefl":"116","workex":"5","research":"0","admit":0},{"index":34,"gpa":6.18,"gre":306.0,"toefl":"105","workex":"4","research":"2","admit":0},{"index":35,"gpa":7.68,"gre":317.0,"toefl":"86","workex":"2","research":"3+","admit":1},{"index":36,"gpa":6.74,"gre":329.0,"toefl":"89","workex":"5","research":"none","admit":0},{"index":37,"gpa":8.79,"gre":328.0,"toefl":"119","workex":"1","research":"3","admit":1},{"index":38,"gpa":9.16,"gre":324.0,"toefl":"96","workex":"3","research":"3+","admit":1},{"index":39,"gpa":5.67,"gre":326.0,"toefl":"101","workex":"5+","research":"3+","admit":0},{"index":40,"gpa":8.62,"gre":329.0,"toefl":"108","workex":"4","research":"3+","admit":1},{"index":41,"gpa":6.41,"gre":321.0,"toefl":"94","workex":"2.5","research":"1","admit":0},{"index":42,"gpa":7.34,"gre":338.0,"toefl":"108","workex":"0","research":"3","admit":0},{"index":43,"gpa":7.53,"gre":301.0,"toefl":"109","workex":"4","research":"0","admit":1},{"index":44,"gpa":6.92,"gre":312.0,"toefl":"100","workex":"4.5","research":"0","admit":0},{"index":45,"gpa":8.51,"gre":null,"toefl":"99","workex":"4","research":"none","admit":0},{"index":46,"gpa":7.98,"gre":301.0,"toefl":"111","workex":"5","research":"0","admit":1},{"index":47,"gpa":5.1,"gre":339.0,"toefl":"111","workex":"3","research":"2","admit":1},{"index":48,"gpa":8.88,"gre":326.0,"toefl":"87","workex":"2.5","research":"2","admit":1},{"index":49,"gpa":5.85,"gre":306.0,"toefl":"111","workex":"1.5","research":"3","admit":1},{"index":50,"gpa":8.94,"gre":307.0,"toefl":"115","workex":"3","research":"0","admit":1},{"index":51,"gpa":5.48,"gre":306.0,"toefl":"90","workex":"3.5","research":"2","admit":1},{"index":52,"gpa":8.03,"gre":307.0,"toefl":"82","workex":"0.5","research":"2","admit":1},{"index":53,"gpa":7.08,"gre":301.0,"toefl":"86","workex":"2.5","research":"2","admit":0},{"index":54,"gpa":5.19,"gre":322.0,"toefl":"93","workex":"4.5","research":"3+","admit":1},{"index":55,"gpa":null,"gre":324.0,"toefl":"117","workex":"4.5","research":"0","admit":1},{"index":56,"gpa":6.38,"gre":332.0,"toefl":"84","workex":"2","research":"2","admit":1},{"index":57,"gpa":7.68,"gre":326.0,"toefl":"101","workex":"1.5","research":"1","admit":0},{"index":58,"gpa":6.53,"gre":308.0,"toefl":"88","workex":"3.5","research":"2","admit":0},{"index":59,"gpa":6.17,"gre":307.0,"toefl":"106","workex":"4","research":"3","admit":0},{"index":60,"gpa":7.18,"gre":326.0,"toefl":"110","workex":"5","research":"2","admit":0},{"index":61,"gpa":6.86,"gre":305.0,"toefl":"89","workex":"0","research":"3","admit":0},{"index":62,"gpa":5.94,"gre":327.0,"toefl":"82","workex":"3","research":"1","admit":1},{"index":63,"gpa":6.89,"gre":319.0,"toefl":"94","workex":"3","research":"3","admit":1},{"index":64,"gpa":5.41,"gre":334.0,"toefl":"110","workex":"4","research":"1","admit":1},{"index":65,"gpa":7.69,"gre":305.0,"toefl":"119","workex":"1.5","research":"0","admit":1},{"index":66,"gpa":7.07,"gre":331.0,"toefl":"92","workex":"2","research":"3+","admit":0},{"index":67,"gpa":6.77,"gre":315.0,"toefl":"101","workex":"0.5","research":"0","admit":1},{"index":68,"gpa":5.5,"gre":318.0,"toefl":"na","workex":"5+","research":"1","admit":1},{"index":69,"gpa":8.31,"gre":323.0,"toefl":"97","workex":"3","research":"0","admit":1},{"index":70,"gpa":9.05,"gre":330.0,"toefl":"119","workex":"2","research":"3+","admit":1},{"index":71,"gpa":6.41,"gre":302.0,"toefl":"98","workex":null,"research":"0","admit":1},{"index":72,"gpa":null,"gre":317.0,"toefl":"102","workex":"3","research":"1","admit":0},{"index":73,"gpa":7.24,"gre":312.0,"toefl":"107","workex":"1","research":"0","admit":0},{"index":74,"gpa":6.56,"gre":332.0,"toefl":"112","workex":"1.5","research":"1","admit":0},{"index":75,"gpa":8.86,"gre":321.0,"toefl":"104","workex":"5+","research":"3+","admit":0},{"index":76,"gpa":6.54,"gre":302.0,"toefl":"83","workex":"1","research":"3+","admit":0},{"index":77,"gpa":8.32,"gre":310.0,"toefl":"119","workex":"4.5","research":"3","admit":0},{"index":78,"gpa":8.86,"gre":325.0,"toefl":"103","workex":"0","research":"3+","admit":1},{"index":79,"gpa":7.63,"gre":326.0,"toefl":"88","workex":"1","research":"1","admit":0},{"index":80,"gpa":6.69,"gre":319.0,"toefl":"88","workex":"0.5","research":"0","admit":0},{"index":81,"gpa":6.62,"gre":339.0,"toefl":"80","workex":"4.5","research":"3","admit":1},{"index":82,"gpa":4.11,"gre":318.0,"toefl":"115","workex":"1","research":"3+","admit":1},{"index":83,"gpa":6.81,"gre":307.0,"toefl":"116","workex":"5+","research":"2","admit":1},{"index":84,"gpa":7.05,"gre":321.0,"toefl":"117","workex":"5+","research":"0","admit":0},{"index":85,"gpa":5.29,"gre":307.0,"toefl":"88","workex":null,"research":"3+","admit":1},{"index":86,"gpa":7.6,"gre":304.0,"toefl":"97","workex":"5","research":"1","admit":0},{"index":87,"gpa":7.89,"gre":315.0,"toefl":"98","workex":"0.5","research":"3","admit":1},{"index":88,"gpa":6.75,"gre":318.0,"toefl":"95","workex":"3.5","research":"1","admit":0},{"index":89,"gpa":8.28,"gre":332.0,"toefl":"103","workex":"4.5","research":"1","admit":1},{"index":90,"gpa":8.08,"gre":324.0,"toefl":"109","workex":"3.5","research":"2","admit":0},{"index":91,"gpa":6.48,"gre":320.0,"toefl":"98","workex":"2","research":"3+","admit":0},{"index":92,"gpa":5.27,"gre":301.0,"toefl":"118","workex":"3.5","research":"2","admit":0},{"index":93,"gpa":6.11,"gre":315.0,"toefl":"95","workex":"5+","research":"3","admit":0},{"index":94,"gpa":7.0,"gre":300.0,"toefl":"94","workex":"4.5","research":"3+","admit":1},{"index":95,"gpa":4.96,"gre":303.0,"toefl":"92","workex":"0.5","research":"2","admit":0},{"index":96,"gpa":6.13,"gre":323.0,"toefl":"119","workex":"5+","research":"1","admit":1},{"index":97,"gpa":8.65,"gre":333.0,"toefl":"119","workex":"2.5","research":"2","admit":1},{"index":98,"gpa":5.79,"gre":303.0,"toefl":"91","workex":"5","research":"none","admit":1},{"index":99,"gpa":6.05,"gre":332.0,"toefl":"99","workex":"4.5","research":"0","admit":1}]}'

1. orient='columns'
2. orient='index'
3. orient='values'
4. orient='records'
5. orient='table'
6. orient='split'

## Read HTML

In [41]:
htm = pd.read_html('https://en.wikipedia.org/wiki/Twitter', match='Employees')
htm

[                                                    0  \
 0                                                 NaN
 1   Screenshot The default page shown to logged-ou...
 2                                    Type of business
 3                                        Type of site
 4                                        Available in
 5                                           Traded as
 6                                             Founded
 7                                        Headquarters
 8                                         Area served
 9                                          Founder(s)
 10                                         Key people
 11                                           Industry
 12                                            Revenue
 13                                   Operating income
 14                                         Net income
 15                                       Total assets
 16                                       Total equity
 17                                          Employees
 18                                       Subsidiaries
 19                                                URL
 20                                         Alexa rank
 21                                       Registration
 22                                              Users
 23                                           Launched
 24                                     Current status
 25                                         Written in
 26          [3][4][5][6][7][8][9][10][11][12][13][14]

                                                     1
 0                                                 NaN
 1   Screenshot The default page shown to logged-ou...
 2                                              Public
 3                     News, social networking service
 4                                        Multilingual
 5                         NYSE: TWTRS&P 500 Component
 6                        March 21, 2006; 14 years ago
 7            San Francisco, California, United States
 8                                           Worldwide
 9         Jack DorseyNoah GlassBiz StoneEvan Williams
 10  Omid Kordestani(Executive Chairman)Jack Dorsey...
 11                                           Internet
 12                             US$3.46 billion (2019)
 13                              US$453 million (2018)
 14                             US$1.47 billion (2019)
 15                            US$10.16 billion (2018)
 16                              US$6.8 billion (2018)
 17                          4,600 (September 2019)[1]
 18                                 VinePeriscopeMoPub
 19                                        twitter.com
 20                          44 (Global, April 2020[2]
 21                        Required to do any activity
 22            321 million active users(February 2019)
 23                        July 15, 2006; 13 years ago
 24                                             Active
 25                            JavaRubyScalaJavaScript
 26          [3][4][5][6][7][8][9][10][11][12][13][14]  ,
         Year  Revenuein mil. US$ Net incomein mil. US$  \
 0  2010[259]                  28                   −67
 1  2011[259]                 106                  −164
 2  2012[259]                 317                   −79
 3  2013[259]                 665                  −645
 4  2014[260]                1403                  −578
 5  2015[261]                2218                  −521
 6  2016[262]                2530                  −457
 7  2017[263]                2443                  −108
 8  2018[264]                3042                  1206

    Total assetsin mil. US$  Employees
 0                        0        NaN
 1                      721        NaN
 2                      832        NaN
 3                     3366     2712.0
 4                     5583     3638.0
 5                     6442     3898.0
 6                     6870     3583.0
 7                     7412     3372.0
 8                    10163     3900.0  ]

In [42]:
len(htm)

2

In [44]:
htm[1]

,Year,Revenuein mil. US$,Net incomein mil. US$,Total assetsin mil. US$,Employees
0,2010[259],28,−67,0,NaN
1,2011[259],106,−164,721,NaN
2,2012[259],317,−79,832,NaN
3,2013[259],665,−645,3366,2712.0
4,2014[260],1403,−578,5583,3638.0
5,2015[261],2218,−521,6442,3898.0
6,2016[262],2530,−457,6870,3583.0
7,2017[263],2443,−108,7412,3372.0
8,2018[264],3042,1206,10163,3900.0

## Read Clipboard

In [45]:
pd.read_clipboard()

      name  gre
0     jack  325
1     anna  329
2     mike  300
3  jasmine  338

In [46]:
pd.read_clipboard()

       dateRep  day  month  year  cases  deaths countriesAndTerritories
0   14-04-2020   14      4  2020     58       3             Afghanistan
1   13-04-2020   13      4  2020     52       0             Afghanistan
2   12-04-2020   12      4  2020     34       3             Afghanistan
3   11-04-2020   11      4  2020     37       0             Afghanistan
4   10-04-2020   10      4  2020     61       1             Afghanistan
5   09-04-2020    9      4  2020     56       3             Afghanistan
6   08-04-2020    8      4  2020     30       4             Afghanistan
7   07-04-2020    7      4  2020     38       0             Afghanistan
8   06-04-2020    6      4  2020     29       2             Afghanistan
9   05-04-2020    5      4  2020     35       1             Afghanistan
10  04-04-2020    4      4  2020      0       0             Afghanistan
11  03-04-2020    3      4  2020     43       0             Afghanistan
12  02-04-2020    2      4  2020     26       0             Afghanistan

In [47]:
pd.read_clipboard()

      name    gre
0     jack  325.0
1     anna  329.0
2      300    NaN
3  jasmine  338.0

In [50]:
admits.to_csv('data/admits_new.csv', index=False)

# Tasks

1. Search Wikipedia for "List of Pokemon" and fetch the table containing names of all the Pokemons to ever grace our lives

In [55]:
poke = pd.read_html('https://en.wikipedia.org/wiki/List_of_Pok%C3%A9mon', match='No additional Pokémon')

In [56]:
len(poke)

1

In [62]:
poke[0]

              Generation I                                 Generation II  \
                     Dex #                   Name                  Dex #
0                      001              Bulbasaur                    152
1                      002                Ivysaur                    153
2                      003               Venusaur                    154
3                      004             Charmander                    155
4                      005             Charmeleon                    156
5                      006              Charizard                    157
6                      007               Squirtle                    158
7                      008              Wartortle                    159
8                      009              Blastoise                    160
9                      010               Caterpie                    161
10                     011                Metapod                    162
11                     012             Butterfree                    163
12                     013                 Weedle                    164
13                     014                 Kakuna                    165
14                     015               Beedrill                    166
15                     016                 Pidgey                    167
16                     017              Pidgeotto                    168
17                     018                Pidgeot                    169
18                     019                Rattata                    170
19                     020               Raticate                    171
20                     021                Spearow                    172
21                     022                 Fearow                    173
22                     023                  Ekans                    174
23                     024                  Arbok                    175
24                     025             Pikachu[b]                    176
25                     026                 Raichu                    177
26                     027              Sandshrew                    178
27                     028              Sandslash                    179
28                     029               Nidoran♀                    180
29                     030               Nidorina                    181
..                     ...                    ...                    ...
126                    127                 Pinsir  No additional Pokémon
127                    128                 Tauros  No additional Pokémon
128                    129               Magikarp  No additional Pokémon
129                    130               Gyarados  No additional Pokémon
130                    131                 Lapras  No additional Pokémon
131                    132                  Ditto  No additional Pokémon
132                    133               Eevee[c]  No additional Pokémon
133                    134               Vaporeon  No additional Pokémon
134                    135                Jolteon  No additional Pokémon
135                    136                Flareon  No additional Pokémon
136                    137                Porygon  No additional Pokémon
137                    138              Omanyte ~  No additional Pokémon
138                    139              Omastar ~  No additional Pokémon
139                    140               Kabuto ~  No additional Pokémon
140                    141             Kabutops ~  No additional Pokémon
141                    142           Aerodactyl ~  No additional Pokémon
142                    143                Snorlax  No additional Pokémon
143                    144               Articuno  No additional Pokémon
144                    145                 Zapdos  No additional Pokémon
145                    146                Moltres  No additional Pokémon
146                    147                Dratini  No additional Pokémon
147                    148              Dragonair  No additional Pokémon
148                    149              Dragonite  No additional Pokémon
149                    150                 Mewtwo  No additional Pokémon
150                    151                  Mew ♭  No additional Pokémon
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

                                   Generation III                         \
                      Name                  Dex #                   Name
0                Chikorita                    252                Treecko
1                  Bayleef                    253                Grovyle
2                 Meganium                    254               Sceptile
3                Cyndaquil                    255                Torchic
4                  Quilava                    256              Combusken
5               Typhlosion                    257               Blaziken
6                 Totodile                    258                 Mudkip
7                 Croconaw                    259              Marshtomp
8               Feraligatr                    260               Swampert
9                  Sentret                    261              Poochyena
10                  Furret                    262              Mightyena
11                Hoothoot                    263              Zigzagoon
12                 Noctowl                    264                Linoone
13                  Ledyba                    265                Wurmple
14                  Ledian                    266                Silcoon
15                Spinarak                    267              Beautifly
16                 Ariados                    268                Cascoon
17                  Crobat                    269                 Dustox
18                Chinchou                    270                  Lotad
19                 Lanturn                    271                 Lombre
20                 Pichu ※                    272               Ludicolo
21                Cleffa ※                    273                 Seedot
22             Igglybuff ※                    274                Nuzleaf
23                Togepi ※                    275                Shiftry
24                 Togetic                    276                Taillow
25                    Natu                    277                Swellow
26                    Xatu                    278                Wingull
27                  Mareep                    279               Pelipper
28                 Flaaffy                    280                  Ralts
29                Ampharos                    281                 Kirlia
..                     ...                    ...                    ...
126  No additional Pokémon                    378                 Regice
127  No additional Pokémon                    379              Registeel
128  No additional Pokémon                    380                 Latias
129  No additional Pokémon                    381                 Latios
130  No additional Pokémon                    382                 Kyogre
131  No additional Pokémon                    383                Groudon
132  No additional Pokémon                    384               Rayquaza
133  No additional Pokémon                    385              Jirachi ♭
134  No additional Pokémon                    386            Deoxys ♭[d]
135  No additional Pokémon  No additional Pokémon  No additional Pokémon
136  No additional Pokémon  No additional Pokémon  No additional Pokémon
137  No additional Pokémon  No additional Pokémon  No additional Pokémon
138  No additional Pokémon  No additional Pokémon  No additional Pokémon
139  No additional Pokémon  No additional Pokémon  No additional Pokémon
140  No additional Pokémon  No additional Pokémon  No additional Pokémon
141  No additional Pokémon  No additional Pokémon  No additional Pokémon
142  No additional Pokémon  No additional Pokémon  No additional Pokémon
143  No additional Pokémon  No additional Pokémon  No additional Pokémon
144  No additional Pokémon  No additional Pokémon  No additional Pokémon
145  No additional Pokémon  No additional Pokémon  No additional Pokémon
146  No additional Pokémon  No additional Pokémon  No additional Pokémon
147  No additional Pokémon  No additional Pokémon  No additional Pokémon
148  No additional Pokémon  No additional Pokémon  No additional Pokémon
149  No additional Pokémon  No additional Pokémon  No additional Pokémon
150  No additional Pokémon  No additional Pokémon  No additional Pokémon
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

             Generation IV                        Generation V              \
                     Dex #                   Name        Dex #        Name
0                      387                Turtwig          494   Victini ♭
1                      388                 Grotle          495       Snivy
2                      389               Torterra          496     Servine
3                      390               Chimchar          497   Serperior
4                      391               Monferno          498       Tepig
5                      392              Infernape          499     Pignite
6                      393                 Piplup          500      Emboar
7                      394               Prinplup          501    Oshawott
8                      395               Empoleon          502      Dewott
9                      396                 Starly          503    Samurott
10                     397               Staravia          504      Patrat
11                     398              Staraptor          505     Watchog
12                     399                 Bidoof          506    Lillipup
13                     400                Bibarel          507     Herdier
14                     401              Kricketot          508   Stoutland
15                     402             Kricketune          509    Purrloin
16                     403                  Shinx          510     Liepard
17                     404                  Luxio          511     Pansage
18                     405                 Luxray          512    Simisage
19                     406                Budew ※          513     Pansear
20                     407               Roserade          514    Simisear
21                     408             Cranidos ~          515     Panpour
22                     409            Rampardos ~          516    Simipour
23                     410             Shieldon ~          517       Munna
24                     411            Bastiodon ~          518    Musharna
25                     412                  Burmy          519      Pidove
26                     413               Wormadam          520   Tranquill
27                     414                 Mothim          521    Unfezant
28                     415                 Combee          522     Blitzle
29                     416              Vespiquen          523   Zebstrika
..                     ...                    ...          ...         ...
126  No additional Pokémon  No additional Pokémon          620    Mienshao
127  No additional Pokémon  No additional Pokémon          621   Druddigon
128  No additional Pokémon  No additional Pokémon          622      Golett
129  No additional Pokémon  No additional Pokémon          623      Golurk
130  No additional Pokémon  No additional Pokémon          624    Pawniard
131  No additional Pokémon  No additional Pokémon          625     Bisharp
132  No additional Pokémon  No additional Pokémon          626  Bouffalant
133  No additional Pokémon  No additional Pokémon          627     Rufflet
134  No additional Pokémon  No additional Pokémon          628    Braviary
135  No additional Pokémon  No additional Pokémon          629     Vullaby
136  No additional Pokémon  No additional Pokémon          630   Mandibuzz
137  No additional Pokémon  No additional Pokémon          631     Heatmor
138  No additional Pokémon  No additional Pokémon          632      Durant
139  No additional Pokémon  No additional Pokémon          633       Deino
140  No additional Pokémon  No additional Pokémon          634    Zweilous
141  No additional Pokémon  No additional Pokémon          635   Hydreigon
142  No additional Pokémon  No additional Pokémon          636    Larvesta
143  No additional Pokémon  No additional Pokémon          637   Volcarona
144  No additional Pokémon  No additional Pokémon          638    Cobalion
145  No additional Pokémon  No additional Pokémon          639   Terrakion
146  No additional Pokémon  No additional Pokémon          640    Virizion
147  No additional Pokémon  No additional Pokémon          641    Tornadus
148  No additional Pokémon  No additional Pokémon          642   Thundurus
149  No additional Pokémon  No additional Pokémon          643    Reshiram
150  No additional Pokémon  No additional Pokémon          644      Zekrom
151  No additional Pokémon  No additional Pokémon          645    Landorus
152  No additional Pokémon  No additional Pokémon          646      Kyurem
153  No additional Pokémon  No additional Pokémon          647    Keldeo ♭
154  No additional Pokémon  No additional Pokémon          648  Meloetta ♭
155  No additional Pokémon  No additional Pokémon          649  Genesect ♭

             Generation VI                                Generation VII  \
                     Dex #                   Name                  Dex #
0                      650                Chespin                    722
1                      651              Quilladin                    723
2                      652             Chesnaught                    724
3                      653               Fennekin                    725
4                      654                Braixen                    726
5                      655                Delphox                    727
6                      656                Froakie                    728
7                      657              Frogadier                    729
8                      658               Greninja                    730
9                      659               Bunnelby                    731
10                     660              Diggersby                    732
11                     661             Fletchling                    733
12                     662            Fletchinder                    734
13                     663             Talonflame                    735
14                     664             Scatterbug                    736
15                     665                 Spewpa                    737
16                     666               Vivillon                    738
17                     667                 Litleo                    739
18                     668                 Pyroar                    740
19                     669                Flabébé                    741
20                     670                Floette                    742
21                     671                Florges                    743
22                     672                 Skiddo                    744
23                     673                 Gogoat                    745
24                     674                Pancham                    746
25                     675                Pangoro                    747
26                     676                Furfrou                    748
27                     677                 Espurr                    749
28                     678               Meowstic                    750
29                     679                Honedge                    751
..                     ...                    ...                    ...
126  No additional Pokémon  No additional Pokémon  No additional Pokémon
127  No additional Pokémon  No additional Pokémon  No additional Pokémon
128  No additional Pokémon  No additional Pokémon  No additional Pokémon
129  No additional Pokémon  No additional Pokémon  No additional Pokémon
130  No additional Pokémon  No additional Pokémon  No additional Pokémon
131  No additional Pokémon  No additional Pokémon  No additional Pokémon
132  No additional Pokémon  No additional Pokémon  No additional Pokémon
133  No additional Pokémon  No additional Pokémon  No additional Pokémon
134  No additional Pokémon  No additional Pokémon  No additional Pokémon
135  No additional Pokémon  No additional Pokémon  No additional Pokémon
136  No additional Pokémon  No additional Pokémon  No additional Pokémon
137  No additional Pokémon  No additional Pokémon  No additional Pokémon
138  No additional Pokémon  No additional Pokémon  No additional Pokémon
139  No additional Pokémon  No additional Pokémon  No additional Pokémon
140  No additional Pokémon  No additional Pokémon  No additional Pokémon
141  No additional Pokémon  No additional Pokémon  No additional Pokémon
142  No additional Pokémon  No additional Pokémon  No additional Pokémon
143  No additional Pokémon  No additional Pokémon  No additional Pokémon
144  No additional Pokémon  No additional Pokémon  No additional Pokémon
145  No additional Pokémon  No additional Pokémon  No additional Pokémon
146  No additional Pokémon  No additional Pokémon  No additional Pokémon
147  No additional Pokémon  No additional Pokémon  No additional Pokémon
148  No additional Pokémon  No additional Pokémon  No additional Pokémon
149  No additional Pokémon  No additional Pokémon  No additional Pokémon
150  No additional Pokémon  No additional Pokémon  No additional Pokémon
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

                                  Generation VIII
                      Name                  Dex #                   Name
0                   Rowlet                    810                Grookey
1                  Dartrix                    811               Thwackey
2                Decidueye                    812              Rillaboom
3                   Litten                    813              Scorbunny
4                 Torracat                    814                 Raboot
5               Incineroar                    815              Cinderace
6                  Popplio                    816                 Sobble
7                  Brionne                    817               Drizzile
8                Primarina                    818               Inteleon
9                  Pikipek                    819                Skwovet
10                Trumbeak                    820               Greedent
11               Toucannon                    821               Rookidee
12                 Yungoos                    822            Corvisquire
13                Gumshoos                    823            Corviknight
14                 Grubbin                    824                Blipbug
15               Charjabug                    825                Dottler
16                Vikavolt                    826               Orbeetle
17              Crabrawler                    827                 Nickit

2. The FIFA 20 Dataset contains over 18000 footballers. Read in only the top 3000 names in the list and the four columns containing their name, age, nationality and club. Then convert it into a json file using orient = 'values' and then rename the columns to 'A', 'B' and 'C', 'D'

In [65]:
fifa = pd.read_csv('data/players_fifa20.csv', nrows=3000, usecols=[3, 4, 8, 9])
fifa

,long_name,age,nationality,club
0,Lionel Andrés Messi Cuccittini,32,Argentina,FC Barcelona
1,Cristiano Ronaldo dos Santos Aveiro,34,Portugal,Juventus
2,Neymar da Silva Santos Junior,27,Brazil,Paris Saint-Germain
3,Jan Oblak,26,Slovenia,Atlético Madrid
4,Eden Hazard,28,Belgium,Real Madrid
5,Kevin De Bruyne,28,Belgium,Manchester City
6,Marc-André ter Stegen,27,Germany,FC Barcelona
7,Virgil van Dijk,27,Netherlands,Liverpool
8,Luka Modrić,33,Croatia,Real Madrid
9,Mohamed Salah Ghaly,27,Egypt,Liverpool
10,Kylian Mbappé,20,France,Paris Saint-Germain
11,Kalidou Koulibaly,28,Senegal,Napoli
12,Harry Kane,25,England,Tottenham Hotspur
13,Alisson Ramses Becker,26,Brazil,Liverpool
14,David De Gea Quintana,28,Spain,Manchester United
15,N'Golo Kanté,28,France,Chelsea
16,Giorgio Chiellini,34,Italy,Juventus
17,Sergio Leonel Agüero del Castillo,31,Argentina,Manchester City
18,Sergio Ramos García,33,Spain,Real Madrid
19,Luis Alberto Suárez Díaz,32,Uruguay,FC Barcelona
20,Robert Lewandowski,30,Poland,FC Bayern München
21,Sergio Busquets i Burgos,30,Spain,FC Barcelona
22,Antoine Griezmann,28,France,FC Barcelona
23,Paulo Bruno Exequiel Dybala,25,Argentina,Juventus
24,Paul Pogba,26,France,Manchester United
25,Ederson Santana de Moraes,25,Brazil,Manchester City
26,Raheem Sterling,24,England,Manchester City
27,Christian Dannemann Eriksen,27,Denmark,Tottenham Hotspur
28,Thibaut Courtois,27,Belgium,Real Madrid
29,Gerard Piqué Bernabéu,32,Spain,FC Barcelona
...,...,...,...,...
2970,Alexander Walke,36,Germany,FC Red Bull Salzburg
2971,Arouna Koné,35,Ivory Coast,Sivasspor
2972,Selçuk İnan,34,Turkey,Galatasaray SK
2973,Luis Antonio Jiménez Garcés,35,Chile,Al Ittihad
2974,Goran Pandev,35,FYR Macedonia,Genoa
2975,Bruno Eduardo Regufe Alves,37,Portugal,Parma
2976,Igor Angulo Albóniga,35,Spain,Górnik Zabrze
2977,Christian Fuchs,33,Austria,Leicester City
2978,Federico Marchetti,36,Italy,Genoa
2979,Gonzalo Javier Rodríguez,35,Argentina,San Lorenzo de Almagro
2980,Javier Marcelo Gandolfi,38,Argentina,Club Atlético Talleres
2981,Román Fernando Martínez,36,Argentina,Club Atlético Aldosivi
2982,Mikel Rico Moreno,34,Spain,SD Huesca
2983,Javier Fuego Martínez,35,Spain,Real Sporting de Gijón
2984,Artem Rebrov,35,Russia,Spartak Moscow
2985,Paul Verhaegh,35,Netherlands,FC Twente
2986,Vincent De Marconnay,36,France,Paris FC
2987,Juan Manuel Insaurralde,34,Argentina,Colo-Colo
2988,Jean-Louis Leca,33,France,Racing Club de Lens
2989,이청용 李青龙,30,Korea Republic,VfL Bochum 1848
2990,Aiden McGeady,33,Republic of Ireland,Sunderland
2991,Joe Lewis,31,England,Aberdeen
2992,Neri Raúl Cardozo,32,Argentina,Defensa y Justicia
2993,Marco Russ,33,Germany,Eintracht Frankfurt
2994,Philipp Tschauner,33,Germany,RB Leipzig
2995,Christian Gentner,33,Germany,1. FC Union Berlin
2996,Mario Sebastián Viera Galain,36,Uruguay,Junior FC
2997,Marcos Alberto Angeleri,36,Argentina,Argentinos Juniors
2998,Steven Naismith,32,Scotland,Heart of Midlothian
2999,John Michael Nchekwube Obinna,32,Nigeria,Trabzonspor

In [66]:
fifa.to_json('data/fifa_json.json', orient='values')

In [69]:
fifa_json = pd.read_json('data/fifa_json.json', orient='values')
fifa_json

,0,1,2,3
0,Lionel Andrés Messi Cuccittini,32,Argentina,FC Barcelona
1,Cristiano Ronaldo dos Santos Aveiro,34,Portugal,Juventus
2,Neymar da Silva Santos Junior,27,Brazil,Paris Saint-Germain
3,Jan Oblak,26,Slovenia,Atlético Madrid
4,Eden Hazard,28,Belgium,Real Madrid
5,Kevin De Bruyne,28,Belgium,Manchester City
6,Marc-André ter Stegen,27,Germany,FC Barcelona
7,Virgil van Dijk,27,Netherlands,Liverpool
8,Luka Modrić,33,Croatia,Real Madrid
9,Mohamed Salah Ghaly,27,Egypt,Liverpool
10,Kylian Mbappé,20,France,Paris Saint-Germain
11,Kalidou Koulibaly,28,Senegal,Napoli
12,Harry Kane,25,England,Tottenham Hotspur
13,Alisson Ramses Becker,26,Brazil,Liverpool
14,David De Gea Quintana,28,Spain,Manchester United
15,N'Golo Kanté,28,France,Chelsea
16,Giorgio Chiellini,34,Italy,Juventus
17,Sergio Leonel Agüero del Castillo,31,Argentina,Manchester City
18,Sergio Ramos García,33,Spain,Real Madrid
19,Luis Alberto Suárez Díaz,32,Uruguay,FC Barcelona
20,Robert Lewandowski,30,Poland,FC Bayern München
21,Sergio Busquets i Burgos,30,Spain,FC Barcelona
22,Antoine Griezmann,28,France,FC Barcelona
23,Paulo Bruno Exequiel Dybala,25,Argentina,Juventus
24,Paul Pogba,26,France,Manchester United
25,Ederson Santana de Moraes,25,Brazil,Manchester City
26,Raheem Sterling,24,England,Manchester City
27,Christian Dannemann Eriksen,27,Denmark,Tottenham Hotspur
28,Thibaut Courtois,27,Belgium,Real Madrid
29,Gerard Piqué Bernabéu,32,Spain,FC Barcelona
...,...,...,...,...
2970,Alexander Walke,36,Germany,FC Red Bull Salzburg
2971,Arouna Koné,35,Ivory Coast,Sivasspor
2972,Selçuk İnan,34,Turkey,Galatasaray SK
2973,Luis Antonio Jiménez Garcés,35,Chile,Al Ittihad
2974,Goran Pandev,35,FYR Macedonia,Genoa
2975,Bruno Eduardo Regufe Alves,37,Portugal,Parma
2976,Igor Angulo Albóniga,35,Spain,Górnik Zabrze
2977,Christian Fuchs,33,Austria,Leicester City
2978,Federico Marchetti,36,Italy,Genoa
2979,Gonzalo Javier Rodríguez,35,Argentina,San Lorenzo de Almagro
2980,Javier Marcelo Gandolfi,38,Argentina,Club Atlético Talleres
2981,Román Fernando Martínez,36,Argentina,Club Atlético Aldosivi
2982,Mikel Rico Moreno,34,Spain,SD Huesca
2983,Javier Fuego Martínez,35,Spain,Real Sporting de Gijón
2984,Artem Rebrov,35,Russia,Spartak Moscow
2985,Paul Verhaegh,35,Netherlands,FC Twente
2986,Vincent De Marconnay,36,France,Paris FC
2987,Juan Manuel Insaurralde,34,Argentina,Colo-Colo
2988,Jean-Louis Leca,33,France,Racing Club de Lens
2989,이청용 李青龙,30,Korea Republic,VfL Bochum 1848
2990,Aiden McGeady,33,Republic of Ireland,Sunderland
2991,Joe Lewis,31,England,Aberdeen
2992,Neri Raúl Cardozo,32,Argentina,Defensa y Justicia
2993,Marco Russ,33,Germany,Eintracht Frankfurt
2994,Philipp Tschauner,33,Germany,RB Leipzig
2995,Christian Gentner,33,Germany,1. FC Union Berlin
2996,Mario Sebastián Viera Galain,36,Uruguay,Junior FC
2997,Marcos Alberto Angeleri,36,Argentina,Argentinos Juniors
2998,Steven Naismith,32,Scotland,Heart of Midlothian
2999,John Michael Nchekwube Obinna,32,Nigeria,Trabzonspor

In [71]:
fifa_json.columns = ['A', 'B', 'C', 'D'] # manually setting the column names

In [72]:
fifa_json

,A,B,C,D
0,Lionel Andrés Messi Cuccittini,32,Argentina,FC Barcelona
1,Cristiano Ronaldo dos Santos Aveiro,34,Portugal,Juventus
2,Neymar da Silva Santos Junior,27,Brazil,Paris Saint-Germain
3,Jan Oblak,26,Slovenia,Atlético Madrid
4,Eden Hazard,28,Belgium,Real Madrid
5,Kevin De Bruyne,28,Belgium,Manchester City
6,Marc-André ter Stegen,27,Germany,FC Barcelona
7,Virgil van Dijk,27,Netherlands,Liverpool
8,Luka Modrić,33,Croatia,Real Madrid
9,Mohamed Salah Ghaly,27,Egypt,Liverpool
10,Kylian Mbappé,20,France,Paris Saint-Germain
11,Kalidou Koulibaly,28,Senegal,Napoli
12,Harry Kane,25,England,Tottenham Hotspur
13,Alisson Ramses Becker,26,Brazil,Liverpool
14,David De Gea Quintana,28,Spain,Manchester United
15,N'Golo Kanté,28,France,Chelsea
16,Giorgio Chiellini,34,Italy,Juventus
17,Sergio Leonel Agüero del Castillo,31,Argentina,Manchester City
18,Sergio Ramos García,33,Spain,Real Madrid
19,Luis Alberto Suárez Díaz,32,Uruguay,FC Barcelona
20,Robert Lewandowski,30,Poland,FC Bayern München
21,Sergio Busquets i Burgos,30,Spain,FC Barcelona
22,Antoine Griezmann,28,France,FC Barcelona
23,Paulo Bruno Exequiel Dybala,25,Argentina,Juventus
24,Paul Pogba,26,France,Manchester United
25,Ederson Santana de Moraes,25,Brazil,Manchester City
26,Raheem Sterling,24,England,Manchester City
27,Christian Dannemann Eriksen,27,Denmark,Tottenham Hotspur
28,Thibaut Courtois,27,Belgium,Real Madrid
29,Gerard Piqué Bernabéu,32,Spain,FC Barcelona
...,...,...,...,...
2970,Alexander Walke,36,Germany,FC Red Bull Salzburg
2971,Arouna Koné,35,Ivory Coast,Sivasspor
2972,Selçuk İnan,34,Turkey,Galatasaray SK
2973,Luis Antonio Jiménez Garcés,35,Chile,Al Ittihad
2974,Goran Pandev,35,FYR Macedonia,Genoa
2975,Bruno Eduardo Regufe Alves,37,Portugal,Parma
2976,Igor Angulo Albóniga,35,Spain,Górnik Zabrze
2977,Christian Fuchs,33,Austria,Leicester City
2978,Federico Marchetti,36,Italy,Genoa
2979,Gonzalo Javier Rodríguez,35,Argentina,San Lorenzo de Almagro
2980,Javier Marcelo Gandolfi,38,Argentina,Club Atlético Talleres
2981,Román Fernando Martínez,36,Argentina,Club Atlético Aldosivi
2982,Mikel Rico Moreno,34,Spain,SD Huesca
2983,Javier Fuego Martínez,35,Spain,Real Sporting de Gijón
2984,Artem Rebrov,35,Russia,Spartak Moscow
2985,Paul Verhaegh,35,Netherlands,FC Twente
2986,Vincent De Marconnay,36,France,Paris FC
2987,Juan Manuel Insaurralde,34,Argentina,Colo-Colo
2988,Jean-Louis Leca,33,France,Racing Club de Lens
2989,이청용 李青龙,30,Korea Republic,VfL Bochum 1848
2990,Aiden McGeady,33,Republic of Ireland,Sunderland
2991,Joe Lewis,31,England,Aberdeen
2992,Neri Raúl Cardozo,32,Argentina,Defensa y Justicia
2993,Marco Russ,33,Germany,Eintracht Frankfurt
2994,Philipp Tschauner,33,Germany,RB Leipzig
2995,Christian Gentner,33,Germany,1. FC Union Berlin
2996,Mario Sebastián Viera Galain,36,Uruguay,Junior FC
2997,Marcos Alberto Angeleri,36,Argentina,Argentinos Juniors
2998,Steven Naismith,32,Scotland,Heart of Midlothian
2999,John Michael Nchekwube Obinna,32,Nigeria,Trabzonspor

## Thank you! and see you soon!